const pw=await import(process.env.STUDIO_PLAYWRIGHT_MODULE||'playwright');
const chromium=pw.chromium||pw.default?.chromium;
import {createApp} from '../server/app.mjs';
import sharp from 'sharp';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const evidenceDir=process.env.STUDIO_BROWSER_EVIDENCE_DIR||path.join(tmpdir(),'chicong-slug-evidence');
const dir=await mkdtemp(path.join(tmpdir(),'chicong-slug-browser-'));
const instance=await createApp({dataDir:dir,env:{}});
const server=instance.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base='http://127.0.0.1:'+server.address().port;
let browser;
try{
 browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);
 const errors=[];page.on('pageerror',err=>errors.push(err.message));
 await page.goto(base+'/admin');
 await page.getByLabel('Email quản trị').fill('browser@example.com');await page.getByLabel('Mật khẩu',{exact:true}).fill('browser-test-password');await page.getByRole('button',{name:'Tạo studio',exact:true}).click();
 await page.getByRole('button',{name:'Tạo album',exact:true}).click();
 const form=page.locator('[data-form=album]');
 await form.locator('[name=title]').fill('Đám cưới Đà Lạt — Tuấn & Lan');
 assert.equal(await form.locator('[data-slug-preview]').textContent(),'chicongphoto.vn/album/dam-cuoi-da-lat-tuan-lan');
 await form.locator('[name=status]').selectOption('published');await form.getByRole('button',{name:'Tạo album',exact:true}).click();
 await page.getByRole('button',{name:'Thông tin album'}).waitFor();
 const id=new URL(page.url()).hash.slice('#album/'.length);assert.match(id,/^[a-f0-9]{32}$/);
 await page.getByRole('button',{name:'Thông tin album'}).click();
 assert.equal(await form.locator('[name=slug]').inputValue(),'dam-cuoi-da-lat-tuan-lan');
 await form.locator('[name=title]').fill('Tên đã thay đổi');assert.equal(await form.locator('[name=slug]').inputValue(),'dam-cuoi-da-lat-tuan-lan');
 await form.locator('[name=slug]').fill('Ảnh cưới Đà Lạt');assert.equal(await form.locator('[data-slug-preview]').textContent(),'chicongphoto.vn/album/anh-cuoi-da-lat');
 await mkdir(evidenceDir,{recursive:true});
 await page.screenshot({path:path.join(evidenceDir,'admin-desktop.png'),fullPage:true});
 await form.getByRole('button',{name:'Lưu thay đổi'}).click();await page.locator('#editor').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#toast')?.textContent==='Đã lưu album.');
 await page.waitForFunction(()=>document.querySelector('a[href^="/album/"]')?.getAttribute('href')!=='/album/dam-cuoi-da-lat-tuan-lan');await page.getByRole('link',{name:'Xem trên website'}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Xem trên website'}).getAttribute('href'),'/album/anh-cuoi-da-lat');
 // Upload through the actual admin form, then configure the hero using its saved photo ID.
 const image=await sharp({create:{width:1200,height:800,channels:3,background:'#536e5c'}}).jpeg().toBuffer();
 await page.locator('[data-form=upload] input[type=file]').setInputFiles({name:'wedding.jpg',mimeType:'image/jpeg',buffer:image});
 await page.getByRole('button',{name:'Upload ảnh',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.admin-photo-grid img')?.complete);
 const photo=await instance.db.get('SELECT id FROM photos WHERE album_id=?',[id]);
 await instance.db.run('UPDATE settings SET value=? WHERE key=?',[JSON.stringify([{albumId:id,wideId:photo.id,tallId:photo.id}]),'heroSelection']);
 await instance.db.run('UPDATE settings SET value=? WHERE key=?',[JSON.stringify([{albumId:id,photoId:photo.id}]),'storySelection']);
 await page.goto(base+'/');await page.locator('.highlight-album').waitFor();
 assert.equal(await page.locator('.highlight-album').getAttribute('href'),'/album/anh-cuoi-da-lat');assert.equal(await page.locator('.album-card').first().getAttribute('href'),'/album/anh-cuoi-da-lat');
 await page.goto(base+'/portfolio');await page.locator('.album-card').first().click();await page.waitForURL(base+'/album/anh-cuoi-da-lat');await page.locator('h1').waitFor();
 assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'),'https://chicongphoto.vn/album/anh-cuoi-da-lat');
 await page.goto(base+'/album/'+id);assert.equal(page.url(),base+'/album/anh-cuoi-da-lat');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/admin#album/'+id);await page.getByRole('button',{name:'Thông tin album'}).click();
 await form.locator('[name=slug]').fill('a'.repeat(120));
 await page.screenshot({path:path.join(evidenceDir,'admin-mobile.png'),fullPage:true});
 const overflow=await page.locator('#editor').evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth}));
 assert.ok(overflow.scroll<=overflow.client+1,'Mobile dialog overflow: '+JSON.stringify(overflow));
 await form.locator('[name=slug]').fill('Đà Lạt trên điện thoại');await form.getByRole('button',{name:'Lưu thay đổi'}).click();await page.locator('#editor').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#toast')?.textContent==='Đã lưu album.');
 await page.getByRole('link',{name:'Xem trên website'}).waitFor();await page.waitForFunction(()=>document.querySelector('a[href^="/album/"]')?.getAttribute('href')==='/album/da-lat-tren-dien-thoai');assert.equal(await page.getByRole('link',{name:'Xem trên website'}).getAttribute('href'),'/album/da-lat-tren-dien-thoai');
 assert.deepEqual(errors,[]);console.log('PASS: Chrome desktop and mobile create/edit/preview/upload, homepage hero/cards, portfolio navigation, ID redirect, canonical and no page errors.');
}finally{await browser?.close();await new Promise(r=>server.close(r));await instance.db.close();await rm(dir,{recursive:true,force:true});}
