import {albumEditorial,photoAlt} from './album-editorial.mjs';
import {initInquiryForm} from './inquiry-form.mjs';
import {currentCopy} from './site-copy.mjs';
import {selectHeroSlides,defaultHeroSelection,parseSelection} from './hero-slides.mjs';
import {initHeroSlideshow} from './hero-slideshow.mjs';
import {curateHome,curatePortfolio,nextStories,defaultStorySelection} from './home-curation.mjs';
import {initPortfolioMotion} from './portfolio-motion.mjs';
import {icon} from './icons.mjs';
import {UploadQueue} from './upload-queue.mjs';
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories={wedding:'Ngày cưới',prewedding:'Pre-wedding',portrait:'Chân dung',lifestyle:'Lifestyle'};
const statuses={draft:'Bản nháp',published:'Công khai',private:'Gallery riêng',archived:'Đã lưu trữ',new:'Mới nhận',contacted:'Đã liên hệ',confirmed:'Đã xác nhận',completed:'Hoàn thành',cancelled:'Đã hủy',submitted:'Khách đã gửi'};
let site={},albums=[],album=null,adminAlbums=[],inquiries=[],dates=[],availability={blocked:[],today:''},adminView='dashboard',adminAlbumId=null,filter='all',selectedOnly=false,lightIndex=0,calendarMonth=new Date(),bookingDate='';
const uploadQueues=new WeakMap();let uploadBusy=false;
window.addEventListener('beforeunload',e=>{if(uploadBusy){e.preventDefault();e.returnValue='';}});
const label=s=>`<p class="label">${s}</p>`;
const button=(text,href,cls='')=>`<a class="btn ${cls}" href="${href}">${text}</a>`;
const dateLabel=s=>s?new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(s+'T12:00:00')):'Chưa chọn ngày';
async function api(url,options={}){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);
 try{
  const response=await fetch(url,{credentials:'same-origin',...options,signal:controller.signal,headers:options.body instanceof FormData?options.headers:{'Content-Type':'application/json',...options.headers}});
  const data=await response.json();
  if(!response.ok)throw Object.assign(new Error(data.error||'Không thực hiện được yêu cầu.'),{status:response.status,data});
  return data;
 }catch(error){if(error.status)throw error;throw Error('Không kết nối được máy chủ. Vui lòng thử lại.');}
 finally{clearTimeout(timer);}
}
const send=(url,data,method='POST')=>api(url,{method,body:JSON.stringify(data)});
let clientGallery=false,pickBusy=false;
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
const badge=status=>`<span class="badge ${esc(status)}">${esc(statuses[status]||status)}</span>`;
const cover=a=>a.photos.find(p=>p.id===a.cover_id)||a.photos[0];
const photoSources=p=>Math.max(p.width,p.height)>900?`${esc(p.thumb)} ${Math.round(p.width*Math.min(1,900/Math.max(p.width,p.height)))}w, ${esc(p.src)} ${p.width}w`:`${esc(p.src)} ${p.width}w`;
const img=(p,cls='',eager=false,responsive=false,sizes='(max-width:750px) calc(100vw - 44px), (max-width:1200px) 44vw, 520px')=>p?`<img src="${esc(p.thumb)}" ${responsive&&Math.max(p.width,p.height)>900?`srcset="${photoSources(p)}" sizes="${esc(sizes)}"`:""} ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async" alt="${esc(photoAlt[p.id]||p.caption)}" width="${p.width}" height="${p.height}" class="${cls}">`:`<div class="empty-cover">${icon('image')}<span>Chưa có ảnh</span></div>`;
function nav(){const pathname=location.pathname;return `<header class="public-nav"><a class="wordmark" href="/">${esc(site.brand)}<span>${esc(site.tagline)}</span></a><button class="mobile-menu" data-action="menu" aria-expanded="false" aria-controls="nav-links">Menu ${icon('menu')}</button><nav id="nav-links" aria-label="Điều hướng"><a href="/portfolio" ${(pathname.startsWith('/portfolio')||pathname.startsWith('/album/'))?'aria-current="page"':''}>Bộ ảnh</a><a href="/about" ${pathname==='/about'?'aria-current="page"':''}>Về mình</a><a href="/contact" ${pathname==='/contact'?'aria-current="page"':''}>Liên hệ</a></nav></header>`;}
function contactLinks(){return `<div class="direct-contact">${site.phone?`<a class="underlink" href="tel:${esc(site.phone.replace(/[^+\d]/g,''))}">${icon('phone')} ${esc(site.phone)}</a>`:''}${site.facebook?`<a class="underlink" href="${esc(site.facebook)}" target="_blank" rel="noopener noreferrer">${icon('facebook')} Nhắn qua Facebook ${icon('external')}</a>`:''}</div>`;}
function footer(){
 const invite=!location.pathname.startsWith('/gallery/')&&location.pathname!=='/contact';
 return `<footer class="public-footer journal-footer"><div class="page-width">${invite?cta():''}<div class="footer-main"><a class="wordmark" href="/">${esc(site.brand)}<span>${esc(site.tagline)}</span></a><nav class="footer-links" aria-label="Liên hệ">${site.facebook?`<a href="${esc(site.facebook)}" target="_blank" rel="noopener noreferrer">${icon('facebook')} Facebook</a>`:''}${site.zalo?`<a href="${esc(site.zalo)}" target="_blank" rel="noopener noreferrer">Zalo ${icon('external')}</a>`:''}${site.instagram?`<a href="${esc(site.instagram)}" target="_blank" rel="noopener noreferrer">Instagram ${icon('external')}</a>`:''}${site.email?`<a href="mailto:${esc(site.email)}">Email ${icon('arrow')}</a>`:''}${site.phone?`<a href="tel:${esc(site.phone.replace(/[^+\d]/g,''))}">${icon('phone')} Điện thoại</a>`:''}</nav></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} ${esc(site.brand)}</span><a href="/admin">Studio</a></div></div></footer>`;
}
function publicPage(body){document.body.classList.add('public-view');$('#root').innerHTML=nav()+`<main id="main">${body}</main>`+footer();initPortfolioMotion($('#main'));initHeroSlideshow($('.highlight-hero'));}
function albumContext(a){return albumEditorial(a)?.summary||(a.id==='f5364d170eb33dd7663dd3a83728e192'?'Film · Sắc màu của một ngày mưa':'');}
function albumCard(a,i=0,preview=null){const photo=preview||cover(a);return `<a href="/album/${a.id}" class="album-card ${preview&&photo.width>photo.height?'landscape-card':''}"><figure class="story-image">${img(photo,'',i===0,true)}</figure><div class="album-meta"><div><p class="label">${esc(categories[a.category])} <span aria-hidden="true">·</span> ${a.photo_count??a.photos.length} ảnh</p><h3>${esc(a.title)}</h3>${albumContext(a)?`<p class="album-context">${esc(albumContext(a))}</p>`:''}</div><span class="story-arrow" aria-hidden="true">${icon('arrow')}</span></div></a>`;}
function cta(){return `<section class="footer-invitation"><h2>Kể mình nghe<br><em>về ngày cưới của bạn.</em></h2><p>Chưa chốt ngày hay chưa biết bắt đầu từ đâu?<br>Mình cùng trao đổi nhé.</p><a class="underlink" href="/contact">Trò chuyện cùng mình ${icon('arrow')}</a></section>`;}
function weddingCopy(){return {headline:site.headline,intro:site.intro};}
function home(){
 const {heroAlbum:hero,heroPhoto,stories:featured}=curateHome(albums,site.storySelection),copy=weddingCopy();
 const highlights=selectHeroSlides(albums,site.heroSelection);
 if(!highlights.length&&hero)highlights.push({album:hero,wide:heroPhoto,tall:heroPhoto});
 publicPage(`<section class="highlight-hero page-width" aria-label="Những khoảnh khắc nổi bật" aria-roledescription="trình chiếu">
 <div class="highlight-stage"><div class="highlight-images">${highlights.map(({album:a,wide,tall},i)=>`<figure class="highlight-slide ${i===0?'is-active':''}" aria-hidden="${i!==0}" data-title="${esc(a.title)}" data-href="/album/${a.id}"><picture><source media="(max-width:750px)" srcset="${photoSources(tall)}" sizes="100vw">${img({...wide,caption:"Khoảnh khắc ngày cưới trong bộ ảnh "+a.title},'',i===0,true,'(max-width:1200px) 90vw, 1120px')}</picture></figure>`).join('')}</div>
 <div class="highlight-copy">${label(esc(site.tagline))}<h1>${copy.headline.split('\n').map((line,i)=>i?'<em>'+esc(line)+'</em>':esc(line)).join('<br>')}</h1></div></div>
 <div class="highlight-bar"><a class="highlight-scroll" href="#stories">Xem các bộ ảnh <span aria-hidden="true">↓</span></a>${highlights.length?`<a class="highlight-album" href="/album/${highlights[0].album.id}">${esc(highlights[0].album.title)} ${icon('arrow')}</a>`:''}${highlights.length>1?`<div class="highlight-controls"><button type="button" data-slide="prev" aria-label="Ảnh trước">←</button><span class="highlight-count" aria-live="off">01 / ${String(highlights.length).padStart(2,'0')}</span><button type="button" data-slide="next" aria-label="Ảnh tiếp theo">→</button><button type="button" data-slide="pause" aria-label="Tạm dừng trình chiếu">Ⅱ</button></div>`:''}</div>
 </section>
 <section class="page-width featured" id="stories"><div class="section-top"><div>${label('BỘ ẢNH ĐƯỢC CHỌN')}<h2>Một vài ngày cưới<br><em>mình đã ghi lại.</em></h2></div><a class="underlink" href="/portfolio">Xem tất cả ${icon('arrow')}</a></div><div class="album-grid selected-grid">${featured.length?featured.map(({album,photo},i)=>albumCard(album,i,photo)).join(''):'<div class="empty-state"><p>Những câu chuyện đang được chuẩn bị. Trong lúc chờ, mình rất vui được nghe về ngày cưới của bạn.</p><a class="underlink" href="/contact">Trò chuyện cùng mình</a></div>'}</div></section>
 <section class="medium-note page-width"><div>${label('CHỤP ẢNH NGÀY CƯỚI')}<h2>Hai bạn tận hưởng.<br><em>Mình ghi lại.</em></h2></div><div><p>Mình tập trung chụp ngày cưới, ghi lại hai bạn bên gia đình, bạn bè và những khoảnh khắc tự nhiên trong ngày. Chia sẻ dự định và ngân sách dự kiến để mình tư vấn cách chụp phù hợp và gửi báo giá riêng.</p><a class="underlink" href="/contact">Chia sẻ dự định của hai bạn ${icon('arrow')}</a></div></section>
 <section class="note-section page-width">${label('NGƯỜI ĐỨNG SAU ỐNG KÍNH')}<p>Mình là ${esc(site.name)}.<br><em>Hơn 5 năm đồng hành<br>cùng những ngày cưới.</em></p><a class="underlink" href="/about">Một chút về mình ${icon('arrow')}</a></section>`);
}
function portfolio(){const availableCategories=Object.entries(categories).filter(([key])=>albums.some(a=>a.category===key));const visible=curatePortfolio(albums,site.storySelection).filter(({album})=>filter==='all'||album.category===filter);publicPage(`<section class="page-width page-title portfolio-title">${label('ẢNH & NHỮNG CÂU CHUYỆN')}<h1>Câu chuyện <em>bằng ảnh.</em></h1><p>Những ngày cưới mình ghi lại bằng film và máy số.</p></section><section class="page-width portfolio-section">${availableCategories.length>1?`<div class="filter-row" role="group" aria-label="Lọc portfolio">${[['all','Tất cả'],...availableCategories].map(([k,v])=>`<button data-action="filter" data-filter="${k}" aria-pressed="${filter===k}" class="${filter===k?'active':''}">${v}</button>`).join('')}</div>`:''}<div class="album-grid stories-grid">${visible.length?visible.map(({album,photo},i)=>albumCard(album,i,photo)).join(''):'<p class="empty-state">Chưa có album trong thể loại này.</p>'}</div></section>`);}
function photosMarkup(photos,client=false){return `<div class="photo-grid">${photos.map((p,i)=>`<article class="photo-item ${!client&&p.width/p.height>1.3&&i%6===0?'photo-wide':''}"><button class="photo-open" data-action="open-photo" data-photo="${p.id}" aria-label="Xem ảnh ${esc(p.caption)}">${img(p,'',i<2,true,client?'(max-width:750px) calc((100vw - 62px)/2), (max-width:1200px) 43vw, 544px':'(max-width:750px) calc(100vw - 40px), (max-width:1200px) 90vw, 1120px')}</button><div class="photo-info"><span>${esc(p.caption||'Ảnh '+(i+1))}</span>${client?`<button class="pick ${p.selected?'picked':''}" data-action="pick" data-photo="${p.id}" aria-pressed="${!!p.selected}" aria-label="${p.selected?'Bỏ chọn':'Chọn'} ảnh ${esc(p.caption)}">${p.selected?'♥':'♡'}</button>`:''}</div></article>`).join('')}</div>`;}
function relatedStories(){
 const stories=nextStories(albums,album.id,site.storySelection);
 if(!stories.length)return '';
 return `<section class="page-width related-stories"><div class="section-top"><div>${label('CÒN NHỮNG ĐIỀU ĐỂ NHỚ')}<h2>Một câu chuyện khác,<br><em>một cảm xúc mới.</em></h2></div><a class="underlink" href="/portfolio">Tất cả bộ ảnh ${icon('arrow')}</a></div><div class="album-grid related-grid">${stories.map(({album,photo},i)=>albumCard(album,i,photo)).join('')}</div></section>`;
}
function albumDescription(a){
 const description=a.description||'';
 const imported={
 'A New Chapter of Love':'Cheers to a new chapter of love! ',
 'Love in the Details':'Love in the details, beauty in every frame. ',
 'Celebrating Love':'Celebrating love and unforgettable moments. ',
 'Traditional Wedding':'Follow my passion for traditional photography. ',
 'Ceremony | T & T':'Ceremony | T & T. '
 };
 let text=description;
 if(imported[a.title]&&text.startsWith(imported[a.title]))text=text.slice(imported[a.title].length);
 const at=text.search(/Photographed for|Photography by|Wedding photography by|Ảnh: Chí Công/);
 const intro=albumEditorial(a)?.intro||(at>=0?text.slice(0,at).trim():text);
 const credit=at>=0?text.slice(at).trim():'';
 return `${intro?`<p class="album-description">${esc(intro)}</p>`:''}${credit?`<p class="album-credit">${esc(credit)}</p>`:''}`;
}
function albumPage(client=false){clientGallery=client;const visible=selectedOnly?album.photos.filter(p=>p.selected):album.photos;const count=album.photos.filter(p=>p.selected).length;publicPage(`<section class="page-width page-title album-title">${label(client?'YOUR PRIVATE GALLERY':esc(categories[album.category]))}<h1>${esc(album.title)}</h1>${client?`<p>${esc(album.description)}</p>`:albumDescription(album)}<div class="album-line"><span>${album.photos.length} ảnh${album.event_date?' · '+dateLabel(album.event_date):''}</span>${client?`<button class="link-btn" data-action="lock-gallery">Đóng gallery</button>`:'<a href="/portfolio">Bộ ảnh</a>'}</div>${client?'':`<a class="underlink album-consult" href="/contact">Trao đổi về bộ ảnh cưới của bạn ${icon('arrow')}</a>`}</section><section class="page-width photo-section ${client?'client-photos':'editorial-photos'}">${client?`<div class="client-toolbar"><div><strong>${count} ảnh đã chọn</strong><p>Bấm ♡ để chọn ảnh. Lựa chọn được lưu khi bạn bấm.</p></div><button class="small-btn" data-action="selected-only" aria-pressed="${selectedOnly}">${selectedOnly?'Xem tất cả':'Chỉ xem đã chọn'}</button><button class="btn" data-action="submit-picks" ${!count?'disabled':''}>${album.selection_status==='submitted'?'Gửi lại lựa chọn':'Gửi lựa chọn'}</button></div>${album.selection_status==='submitted'?'<p class="success-note">Lựa chọn đã được gửi đến studio. Bạn có thể tiếp tục chỉnh và gửi lại.</p>':''}`:''}${visible.length?photosMarkup(visible,client):`<div class="empty-state">${selectedOnly?'Bạn chưa chọn ảnh nào.':'Bộ ảnh đang được chuẩn bị.'}</div>`}</section>${client?'':relatedStories()}`);}
function lockedGallery(){publicPage(`<section class="gallery-lock page-width">${label('A LITTLE SPACE, JUST FOR YOU')}<div class="lock-icon">${icon('lock')}</div><h1>Gallery của bạn.</h1><p>Nhập mật khẩu được nhiếp ảnh gia chia sẻ để xem và chọn ảnh.</p><form data-form="unlock"><label>Mật khẩu gallery<input name="password" type="password" autocomplete="current-password" required autofocus></label><p class="form-error" role="alert"></p><button class="btn">Mở bộ ảnh </button></form></section>`);}
function about(){
 const portrait=/^[a-f0-9]{32}$/.test(site.portrait||'');
 publicPage(`<section class="page-width page-title about-title">${label('VỀ MÌNH')}<h1>Xin chào,<br><em>mình là ${esc(site.name)}.</em></h1><p>${esc(site.tagline)}</p></section>
 <section class="page-width about-layout about-profile ${portrait?'':'without-portrait'}">${portrait?`<figure class="about-art"><img src="/portrait/${site.portrait}" alt="${esc(site.name)} — nhiếp ảnh gia" width="800" height="1000" fetchpriority="high"></figure>`:''}<div class="about-intro"><h2>Những người bạn yêu.<br><em>Ngày bạn muốn nhớ.</em></h2>${site.about.split(/\n\s*\n/).filter(Boolean).map(paragraph=>`<p class="long-copy">${esc(paragraph)}</p>`).join('')}<p class="long-copy">Bạn có thể bắt đầu bằng việc xem các bộ ảnh mình đã thực hiện, rồi kể mình nghe điều bạn mong chờ ở ngày cưới của mình.</p><div class="about-actions">${button('Xem những bộ ảnh','/portfolio','btn-outline')}<a class="underlink" href="/contact">Trò chuyện cùng mình ${icon('arrow')}</a></div></div></section>
 <section class="page-width approach-section">${label('MÌNH BẮT ĐẦU THẾ NÀO')}<h2>Trước ngày cưới,<br><em>mình cùng chuẩn bị.</em></h2><div class="approach-grid"><article><span>01</span><h3>Chia sẻ dự định</h3><p>Ngày cưới dự kiến, địa điểm và những điều bạn muốn có trong bộ ảnh.</p></article><article><span>02</span><h3>Trao đổi cách chụp</h3><p>Cùng xem ảnh tham khảo và trao đổi về film, máy số hoặc kết hợp cả hai.</p></article><article><span>03</span><h3>Thống nhất lịch trình</h3><p>Trao đổi các phần của buổi lễ và những người, những khoảnh khắc quan trọng với bạn.</p></article></div><div class="delivery-note"><h3>Thống nhất trước khi xác nhận lịch</h3><p>Mình cùng hai bạn trao đổi rõ phạm vi buổi chụp, hình thức bàn giao và thời gian nhận ảnh. Báo giá được gửi riêng theo dự định của hai bạn.</p></div></section>`);
}
function calendarHTML(){
 if(availability.loading)return '<p class="form-note" role="status">Đang tải lịch… Bạn vẫn có thể điền thông tin bên dưới.</p>';
 if(availability.unavailable)return '<p class="form-note" role="status">Chưa tải được lịch. Bạn vẫn có thể gửi tư vấn; mình sẽ kiểm tra ngày khi trao đổi.</p><button type="button" class="link-btn" data-action="retry-calendar">Thử tải lại lịch</button>';
 const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth();
 const start=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate();
 const earliest=availability.today.slice(0,7),current=`${year}-${String(month+1).padStart(2,'0')}`;
 return `<div class="calendar-heading"><button type="button" data-action="month-prev" aria-label="Tháng trước" ${current<=earliest?'disabled':''}>←</button><strong aria-live="polite">Tháng ${month+1}, ${year}</strong><button type="button" data-action="month-next" aria-label="Tháng tiếp theo">→</button></div><div class="calendar-grid">${['T2','T3','T4','T5','T6','T7','CN'].map(d=>`<span class="weekday">${d}</span>`).join('')}${Array.from({length:start},()=>'<span></span>').join('')}${Array.from({length:days},(_,i)=>{
 const d=`${current}-${String(i+1).padStart(2,'0')}`,busy=availability.blocked.includes(d),past=d<availability.today;
 return `<button type="button" data-action="choose-date" data-date="${d}" class="${busy?'busy ':''}${d===bookingDate?'chosen':''}" ${busy||past?'disabled':''} aria-pressed="${d===bookingDate}" ${d===availability.today?'aria-current="date"':''} aria-label="${dateLabel(d)}${busy?' — đã kín lịch':past?' — đã qua':''}">${i+1}</button>`;
 }).join('')}</div><div class="calendar-legend"><span><i></i>Có thể gửi yêu cầu</span><span><i class="busy"></i>Đã kín lịch</span></div>`;
}
function syncBookingDate(followMonth=false){
 const input=$('#booking-form [name=date]');if(!input)return;
 bookingDate=input.value;
 if(followMonth&&bookingDate){const [year,month]=bookingDate.split('-').map(Number);calendarMonth=new Date(year,month-1,1);}
 const busy=availability.blocked.includes(bookingDate);
 input.setCustomValidity(busy?'Ngày này đã kín lịch. Vui lòng chọn ngày khác.':'');
 input.setAttribute('aria-invalid',String(!input.validity.valid));
 const feedback=$('#booking-date-feedback');
 feedback.textContent=busy?'Ngày này đã kín lịch. Vui lòng chọn ngày khác.':bookingDate&&bookingDate<availability.today?'Vui lòng chọn ngày từ hôm nay trở đi.':bookingDate?`Ngày dự kiến: ${dateLabel(bookingDate)}. Studio sẽ xác nhận sau khi trao đổi.`:'Chưa chọn ngày? Bạn vẫn có thể gửi yêu cầu để được tư vấn.';
 feedback.classList.toggle('date-unavailable',!input.validity.valid);
 $('[data-action=clear-date]').hidden=!bookingDate;
 $('#booking-calendar').innerHTML=calendarHTML();
}
function contact(){publicPage(`<section class="page-width page-title contact-title">${label('LIÊN HỆ · TP. HỒ CHÍ MINH')}<h1>Bắt đầu bằng<br><em>một lời chào.</em></h1><p>${esc(site.bookingNote)}</p>${contactLinks()}${site.responseNote?`<p class="response-note">${esc(site.responseNote)}</p>`:''}</section>
<section class="page-width booking-layout contact-layout"><form data-form="inquiry" id="booking-form"><label>Tên của bạn *<input name="name" autocomplete="name" required maxlength="100" placeholder="Mình nên gọi bạn là…"></label><p class="form-note" id="contact-hint">Để lại email hoặc số điện thoại để mình phản hồi. Bạn chỉ cần điền một trong hai.</p><div class="form-pair"><label>Email<input name="email" autocomplete="email" type="email" maxlength="150" aria-describedby="contact-hint" placeholder="Email của bạn"></label><label>Điện thoại<input name="phone" type="tel" autocomplete="tel" maxlength="30" aria-describedby="contact-hint" placeholder="Số điện thoại của bạn"></label></div>
<div class="booking-date-field"><label>Ngày cưới dự kiến (không bắt buộc)<input name="date" type="date" min="${availability.today}" value="${bookingDate}" aria-describedby="booking-date-feedback"></label><button type="button" class="link-btn" data-action="clear-date" hidden>Bỏ chọn ngày</button></div><p class="form-note booking-date-feedback" id="booking-date-feedback" role="status">Chưa chốt ngày? Bạn vẫn có thể gửi yêu cầu tư vấn.</p><div class="contact-calendar"><details><summary>Xem lịch nhận yêu cầu</summary><p class="form-note">Chọn ngày dự kiến trên lịch hoặc nhập trực tiếp ở trên.</p><div id="booking-calendar">${calendarHTML()}</div></details></div>
<label>Bạn quan tâm đến<select name="service"><option>Mình muốn được tư vấn thêm</option><option>Chụp ảnh cưới bằng máy số</option><option>Chụp ảnh cưới bằng film</option><option>Kết hợp film và máy số</option></select></label><label>Ngân sách chụp ảnh dự kiến (không bắt buộc)<input name="budget" maxlength="100" aria-describedby="budget-hint" placeholder="Số tiền hoặc khoảng ngân sách bạn dự tính (VNĐ)"></label><p class="form-note" id="budget-hint">Có thể để trống nếu bạn chưa xác định. Mình sẽ gửi báo giá riêng sau khi trao đổi.</p><label>Bạn đang dự định buổi chụp như thế nào? *<textarea name="message" required minlength="10" maxlength="5000" rows="4" placeholder="Ngày cưới dự kiến, lễ gia tiên hay tiệc cưới, điều bạn mong chờ hoặc muốn hỏi…"></textarea></label><div class="trap" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off"></div><p class="form-note">Thông tin chỉ dùng để tư vấn về buổi chụp. Gửi yêu cầu chưa giữ chỗ; lịch chụp được xác nhận sau khi mình trao đổi với bạn.</p><p class="form-error" role="alert"></p><button class="btn" type="submit">Gửi yêu cầu tư vấn ${icon('arrow')}</button></form></section>`);
 initInquiryForm($('#booking-form'),{availability:()=>availability,onDateConflict:()=>loadBookingAvailability(),onSuccess:(result,data)=>{
  const form=$('#booking-form');
  form.innerHTML=`<div class="booking-success" tabindex="-1" role="status"><span>✓</span><h2>Mình đã nhận được<br>yêu cầu tư vấn của bạn.</h2><p>Mã yêu cầu: <strong>${esc(result.reference)}</strong></p><p>Mình sẽ phản hồi qua ${data.email?'email '+esc(data.email):'số điện thoại '+esc(data.phone)} để tư vấn và gửi báo giá riêng.</p>${site.responseNote?`<p>${esc(site.responseNote)}</p>`:''}<p>Yêu cầu này chưa giữ lịch chụp.</p>${site.phone||site.facebook?`<p>Bạn muốn trao đổi trực tiếp?</p>${contactLinks()}`:''}${button('Xem bộ ảnh','/portfolio','btn-outline')}</div>`;
  form.querySelector('.booking-success').focus();
 }});
}
async function loadBookingAvailability(){
 availability={...availability,loading:true,unavailable:false};
 const calendar=$('#booking-calendar');if(calendar)calendar.innerHTML=calendarHTML();
 try{availability=await api('/api/availability');}catch{availability={...availability,loading:false,unavailable:true};}
 if($('#booking-form [name=date]'))syncBookingDate();
}

function loginPage(session){if($('#editor').open)$('#editor').close();if($('#lightbox').open)$('#lightbox').close();$('#root').innerHTML=`<main id="main" class="login-page"><a href="/" class="wordmark">${esc(site.brand)}<span>THE STUDIO</span></a><div class="login-card">${label(session.needsSetup?'WELCOME TO YOUR STUDIO':'YOUR CREATIVE WORKSPACE')}<h1>${session.needsSetup?'Bắt đầu studio.':'Chào mừng trở lại.'}</h1><p>${session.needsSetup?'Tạo tài khoản quản trị của bạn để bắt đầu quản lý website.':'Đăng nhập để quản lý portfolio, gallery và lịch chụp.'}</p><form data-form="${session.needsSetup?'setup':'login'}"><label>Email quản trị<input type="email" name="email" required autocomplete="username"></label><label>Mật khẩu<input type="password" name="password" required ${session.needsSetup?'minlength="12"':''} autocomplete="${session.needsSetup?'new-password':'current-password'}"></label>${session.needsSetup?'<p class="form-note">Mật khẩu tối thiểu 12 ký tự. Bạn tự đặt và giữ mật khẩu này.</p><label>Mã thiết lập <span class="muted">(chỉ cần trên hosting)</span><input name="token" type="password" autocomplete="off"></label>':''}<p class="form-error" role="alert"></p><button class="btn">${session.needsSetup?'Tạo studio':'Đăng nhập'} </button></form></div><a class="underlink" href="/">Về website</a></main>`;}
const views=[['dashboard','grid','Tổng quan'],['portfolio','image','Portfolio'],['clients','gallery','Gallery khách'],['inquiries','inbox','Yêu cầu đặt lịch'],['calendar','calendar','Lịch chụp'],['settings','settings','Website']];
function alignAdminNav(){
 const nav=$('.sidebar nav'),active=nav?.querySelector('[aria-current=page]');
 if(!nav||!active||!window.matchMedia('(max-width:750px)').matches)return;
 const navRect=nav.getBoundingClientRect(),activeRect=active.getBoundingClientRect();
 nav.scrollLeft+=activeRect.left-navRect.left-(nav.clientWidth-activeRect.width)/2;
}
window.addEventListener('resize',alignAdminNav);
function adminShell(content){history.replaceState(null,'','#'+(adminAlbumId?'album/'+adminAlbumId:adminView));$('#root').innerHTML=`<div class="admin-layout"><aside class="sidebar"><a class="wordmark" href="/">${esc(site.brand)}<span>THE STUDIO</span></a><p class="sidebar-label">QUẢN LÝ STUDIO</p><nav aria-label="Điều hướng studio">${views.map(([v,glyph,text])=>`<button data-action="admin-view" data-view="${v}" class="${adminView===v?'active':''}" ${adminView===v?'aria-current="page"':''}>${icon(glyph)}<span>${text}</span></button>`).join('')}</nav><div class="sidebar-bottom"><span class="studio-signature">Một nơi cho những câu chuyện.</span><button data-action="logout">${icon('logout')} Đăng xuất</button></div></aside><main id="main" class="admin-main"><header class="admin-topbar"><div class="breadcrumb"><span>Studio</span><span aria-hidden="true">/</span><strong>${esc(views.find(v=>v[0]===adminView)?.[2])}</strong></div><a href="/" target="_blank" rel="noopener">Xem website ${icon('external')}</a></header><div class="admin-content">${content}</div></main></div>`;alignAdminNav();}
function readinessPanel(r){return `<section class="panel readiness-panel"><div class="panel-heading"><h2>Chuẩn bị mở studio</h2><span class="badge">${r.production?'Đang chạy production':'Bản xem trước trên máy'}</span></div><div class="readiness-grid">${[[r.contact,'Thông tin liên hệ',r.contact?'Khách đã có kênh liên hệ với bạn.':'Thêm email hoặc số điện thoại trong Website.','settings'],[r.portfolio,'Portfolio đầu tiên',r.portfolio?'Đã có bộ ảnh công khai kèm ảnh.':'Đăng ảnh rồi chuyển album sang công khai.','portfolio'],[r.cloud,'Lưu trữ trên host',r.cloud?'Đã cấu hình database và kho ảnh cloud.':'Dữ liệu đang lưu trên máy; cần cấu hình khi đưa lên host.','settings']].map(([done,title,note,view])=>`<button class="readiness-item" data-action="admin-view" data-view="${view}"><span class="readiness-icon ${done?'done':''}">${done?icon('check'):icon('plus')}</span><div><strong>${title}</strong><p>${note}</p></div></button>`).join('')}</div></section>`;}
function adminHeading(title,subtitle,action=''){return `<div class="admin-heading"><div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`;}
function inquiryRows(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Buổi chụp</th><th>Ngày dự kiến</th><th>Trạng thái</th><th><span class="sr-only">Thao tác</span></th></tr></thead><tbody>${rows.map(r=>`<tr data-search="${esc([r.name,r.email,r.phone,r.service,r.date].join(' '))}" data-status="${r.status}"><td class="customer-cell" data-label="Khách hàng"><strong>${esc(r.name)}</strong><small>${esc(r.email||r.phone)}</small></td><td data-label="Dịch vụ">${esc(r.service)}</td><td data-label="Ngày dự kiến">${dateLabel(r.date)}</td><td class="status-cell" data-label="Trạng thái">${badge(r.status)}</td><td class="row-action"><button class="link-btn" data-action="inquiry-detail" data-id="${r.id}" aria-label="Xem yêu cầu của ${esc(r.name)}">Xem chi tiết ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty-state"><span class="empty-icon">${icon('inbox')}</span><h3>Chưa có yêu cầu đặt lịch</h3><p>Khi khách gửi lời nhắn, bạn sẽ thấy tại đây.</p></div>`;}
async function dashboard(){const d=await api('/api/admin/dashboard');const count=(rows,status)=>Number(rows.find(r=>r.status===status)?.count||0);adminShell(adminHeading('Tổng quan','Mọi câu chuyện, cuộc hẹn và lựa chọn trong studio.',`<button class="btn" data-action="new-album">${icon('plus')} Tạo album</button>`)+`<div class="stats-grid">${[['Portfolio công khai',count(d.albums,'published'),'Bộ ảnh đang hiển thị'],['Gallery khách',count(d.albums,'private'),'Không gian riêng cho khách'],['Yêu cầu mới',count(d.inquiries,'new'),'Đang chờ bạn xử lý'],['Ảnh trong studio',d.photos,'Khoảnh khắc được lưu giữ']].map(([title,n,note])=>`<div class="stat-card"><span>${title}</span><strong>${n}</strong><small>${note}</small></div>`).join('')}</div>${readinessPanel(d.readiness)}<section class="panel"><div class="panel-heading"><h2>Yêu cầu gần đây</h2><button class="link-btn" data-action="admin-view" data-view="inquiries">Xem tất cả</button></div>${inquiryRows(d.recent)}</section><div class="admin-two"><section class="panel quick-start"><h2>Bắt đầu một bộ ảnh.</h2><p>Tạo album, thêm ảnh, chọn bìa và chuyển sang công khai khi đã sẵn sàng.</p><button class="underlink" data-action="new-album">Tạo album đầu tiên</button></section><section class="panel"><h2>Khách đã gửi lựa chọn</h2>${d.selections.length?d.selections.map(a=>`<button class="selection-alert" data-action="edit-album" data-id="${a.id}"><span>${esc(a.title)}</span></button>`).join(''):'<p class="muted panel-note">Khi khách gửi danh sách ảnh đã chọn, bạn sẽ thấy gallery tại đây.</p>'}</section></div>`);}
function adminAlbumsPage(){const client=adminView==='clients';const rows=adminAlbums.filter(a=>client?a.status==='private':a.status!=='private');adminShell(adminHeading(client?'Gallery khách':'Portfolio',client?'Chia sẻ link và mật khẩu. Khách xem ảnh, chọn và gửi lại cho studio.':'Tạo bộ ảnh, sắp xếp nội dung và chọn những gì sẽ hiển thị trên website.',`<button class="btn" data-action="new-album">${icon('plus')} ${client?'Tạo gallery':'Tạo album'}</button>`)+searchToolbar(client?['private']:['draft','published','archived'])+`<div class="admin-album-grid">${rows.length?rows.map(a=>`<button class="admin-album" data-search="${esc([a.title,a.client_name,categories[a.category]].join(' '))}" data-status="${a.status}" data-action="edit-album" data-id="${a.id}">${img(cover(a))}<div class="admin-album-info">${badge(a.status)}<h3>${esc(a.title)}</h3><p>${a.photos.length} ảnh · ${esc(categories[a.category])}${client?' · '+a.photos.filter(p=>p.selected).length+' đã chọn':''}</p>${a.selection_status==='submitted'&&client?'<span class="pick-status">● Khách đã gửi lựa chọn</span>':''}</div></button>`).join(''):`<div class="empty-state"><span class="empty-icon">${icon('image')}</span><h3>${client?'Gallery đầu tiên của bạn':'Bộ ảnh đầu tiên của bạn'}</h3><p>${client?'Tạo gallery để chia sẻ ảnh riêng với khách.':'Thêm một bộ ảnh để bắt đầu câu chuyện.'}</p></div>`}</div>`);applyAdminFilters();}
function albumForm(a={}){return `<form data-form="album" data-id="${a.id||''}"><label>Tên album *<input name="title" required maxlength="150" value="${esc(a.title)}" placeholder="Tên câu chuyện của bạn"></label><div class="form-pair"><label>Thể loại<select name="category">${Object.entries(categories).map(([k,v])=>`<option value="${k}" ${a.category===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Trạng thái<select name="status">${['draft','published','private','archived'].map(k=>`<option value="${k}" ${(a.status|| (adminView==='clients'?'private':'draft'))===k?'selected':''}>${statuses[k]}</option>`).join('')}</select></label></div><label>Mô tả<textarea name="description" rows="3" maxlength="2000">${esc(a.description)}</textarea></label><div class="form-pair"><label>Tên khách hàng<input name="client_name" maxlength="150" value="${esc(a.client_name)}"></label><label>Ngày chụp<input name="event_date" type="date" value="${esc(a.event_date)}"></label></div><label>Mật khẩu gallery riêng<input name="password" type="password" autocomplete="new-password" minlength="8" placeholder="${a.has_password?'Để trống nếu giữ mật khẩu hiện tại':'Ít nhất 8 ký tự nếu chọn gallery riêng'}"></label><p class="form-note">Chỉ trạng thái công khai hiển thị trên portfolio. Gallery riêng cần mật khẩu; đổi mật khẩu sẽ yêu cầu khách đăng nhập lại.</p><p class="form-error" role="alert"></p><button class="btn">${a.id?'Lưu thay đổi':'Tạo album'} </button></form>`;}
function managedPhotos(a){return a.photos.map((p,i)=>`<article class="manage-photo ${p.selected?'client-picked':''}">${img(p)}<div><span class="photo-number">${String(i+1).padStart(2,'0')}${p.selected?' · ♥ Khách chọn':''}</span><p>${esc(p.original||p.caption)}</p><div class="photo-actions"><button data-action="cover-photo" data-id="${p.id}">${a.cover_id===p.id?'● Ảnh bìa':'Đặt bìa'}</button><button data-action="caption-photo" data-id="${p.id}">Sửa</button><button data-action="move-photo" data-id="${p.id}" data-direction="up" aria-label="Đưa ảnh lên trước" ${i===0?'disabled':''}>↑</button><button data-action="move-photo" data-id="${p.id}" data-direction="down" aria-label="Đưa ảnh xuống sau" ${i===a.photos.length-1?'disabled':''}>↓</button><button data-action="remove-photo" data-id="${p.id}">Xóa</button></div></div></article>`).join('');}
function adminAlbumDetail(){const a=adminAlbums.find(a=>a.id===adminAlbumId);if(!a){adminAlbumId=null;return adminAlbumsPage();}adminView=a.status==='private'?'clients':'portfolio';const count=a.photos.filter(p=>p.selected).length;adminShell(`<button class="underlink back-btn" data-action="album-back">Danh sách album</button>`+adminHeading(esc(a.title),`${a.photos.length} ảnh · ${esc(categories[a.category])}`,`<button class="small-btn" data-action="album-settings" data-id="${a.id}">${icon('settings')} Thông tin album</button>`)+`<div class="album-detail-top">${badge(a.status)}${a.status==='published'?`<a class="underlink" href="/album/${a.id}" target="_blank" rel="noopener">Xem trên website</a>`:''}${a.status==='private'?`<button class="underlink" data-action="copy-link" data-id="${a.id}">Sao chép link gallery</button><span>${count} ảnh được chọn</span><a class="small-btn" href="/api/admin/albums/${a.id}/selections.csv">Xuất danh sách CSV</a>${badge(a.selection_status)}`:''}</div><section class="upload-panel"><div><h3>Thêm những khoảnh khắc.</h3><p>JPEG, PNG, WebP · Tối đa 8MB/ảnh. Chọn nhiều ảnh cùng lúc; ảnh được tối ưu để xem trên web.</p></div><form data-form="upload" data-id="${a.id}"><label class="upload-label">Chọn ảnh<input type="file" name="photos" accept="image/jpeg,image/png,image/webp" multiple required></label><button class="btn" type="submit">Upload ảnh</button><p class="form-error" role="alert"></p></form></section><div class="admin-photo-grid">${managedPhotos(a)}</div>`);}
const adminFilters={};
const normalizeSearch=value=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
function searchToolbar(options){const f=adminFilters[adminView]||{query:'',status:''};return `<div class="admin-filters"><label>Tìm kiếm<span class="search-input">${icon('search')}<input type="search" data-admin-search value="${esc(f.query)}" placeholder="${adminView==='inquiries'?'Tên, email hoặc số điện thoại…':'Tên album hoặc khách hàng…'}"></span></label><label>Trạng thái<select data-admin-status aria-label="Trạng thái"><option value="">Tất cả trạng thái</option>${options.map(k=>`<option value="${k}" ${f.status===k?'selected':''}>${statuses[k]}</option>`).join('')}</select></label><p data-filter-count role="status"></p></div><p class="filter-empty" hidden>Không có kết quả phù hợp. Thử từ khóa hoặc trạng thái khác.</p>`;}
function applyAdminFilters(){if(!$('[data-admin-search]'))return;const f=adminFilters[adminView]||{query:'',status:''};const rows=[...document.querySelectorAll('[data-search]')];let count=0;rows.forEach(row=>{row.hidden=!!((f.status&&row.dataset.status!==f.status)||!normalizeSearch(row.dataset.search).includes(normalizeSearch(f.query.trim())));if(!row.hidden)count++;});$('[data-filter-count]').textContent=`${count} / ${rows.length} kết quả`;$('.filter-empty').hidden=!rows.length||count>0;}
function changeAdminFilter(){adminFilters[adminView]={query:$('[data-admin-search]').value,status:$('[data-admin-status]').value};applyAdminFilters();}
document.addEventListener('input',e=>{if(e.target.matches('[data-admin-search]'))changeAdminFilter();});
document.addEventListener('change',e=>{if(e.target.matches('#booking-form [name=date]'))syncBookingDate(true);if(e.target.matches('[data-admin-status]'))changeAdminFilter();if(e.target.matches('input[type=file]')){const form=e.target.closest('[data-form=upload]');if(form){uploadQueues.delete(form);form.querySelector('button').textContent='Upload ảnh';form.querySelector('.form-error').textContent='';}}});
function inquiriesPage(){adminShell(adminHeading('Yêu cầu đặt lịch','Theo dõi cuộc hẹn và giữ mọi trao đổi ở cùng một nơi.')+searchToolbar(['new','contacted','confirmed','completed','cancelled'])+`<section class="panel">${inquiryRows(inquiries)}</section>`);applyAdminFilters();}
function calendarAdmin(){adminShell(adminHeading('Lịch chụp','Quản lý ngày bận và những buổi chụp đã xác nhận.')+`<div class="admin-two"><section class="panel"><h2>Chặn một ngày</h2><form data-form="block-date"><label>Ngày bận<input name="date" type="date" required></label><label>Ghi chú riêng<input name="note" maxlength="200" placeholder="Chụp ngoài tỉnh, nghỉ…"></label><p class="form-error" role="alert"></p><button class="btn">${icon('plus')} Chặn ngày</button></form></section><section class="panel"><h2>Ngày đã chặn</h2>${dates.length?dates.map(d=>`<div class="date-row"><div><strong>${dateLabel(d.date)}</strong><small>${esc(d.note)}</small></div><button class="link-btn" data-action="unblock-date" data-date="${d.date}">Mở lại</button></div>`).join(''):'<p class="panel-note muted">Chưa chặn ngày nào.</p>'}</section></div><section class="panel"><h2>Lịch đã xác nhận</h2>${inquiryRows(inquiries.filter(i=>i.status==='confirmed'))}</section>`);}
function curationRow(kind,index,choice={}){
 const available=adminAlbums.filter(a=>a.status==='published'&&a.photos.length);
 const selected=available.find(a=>a.id===choice.albumId);
 const photoSelect=(field,title)=>{const selectedPhoto=selected?.photos.find(p=>p.id===choice[field])|| (selected?cover(selected):null);return `<label>${title}<select data-photo-field="${field}" ${selected?'':'disabled'}>${selected?selected.photos.map((p,i)=>`<option value="${p.id}" ${p.id===selectedPhoto?.id?'selected':''}>${i+1}. ${esc(p.caption||'Ảnh')} · ${p.width>p.height?'Ngang':'Dọc'}</option>`).join(''):'<option>Chọn album trước</option>'}</select>${selectedPhoto?`<img class="curation-preview" src="${esc(selectedPhoto.thumb)}" alt="Xem trước ${esc(title)}">`:''}</label>`;};
 return `<fieldset class="curation-row" data-curation="${kind}" data-slot="${index}"><legend>${kind==='hero'?'Slide':'Bộ ảnh'} ${index+1}</legend><label>Album<select data-curation-album><option value="">Không chọn</option>${available.map(a=>`<option value="${a.id}" ${a.id===selected?.id?'selected':''}>${esc(a.title)}</option>`).join('')}</select></label><div class="curation-photos">${kind==='hero'?photoSelect('wideId','Ảnh máy tính')+photoSelect('tallId','Ảnh điện thoại'):photoSelect('photoId','Ảnh đại diện')}</div></fieldset>`;
}
function settingsPage(){
 const fields=[['brand','Tên thương hiệu'],['name','Tên để khách gọi bạn'],['tagline','Dòng mô tả thương hiệu'],['headline','Tiêu đề trang chủ'],['intro','Mô tả khi chia sẻ link'],['about','Giới thiệu bản thân'],['email','Email liên hệ'],['phone','Điện thoại công khai'],['facebook','Link Facebook'],['instagram','Link Instagram'],['zalo','Link Zalo (nếu sử dụng)'],['bookingNote','Lời mở đầu trang liên hệ'],['responseNote','Thời gian phản hồi thực tế (để trống nếu chưa cam kết)']];
 const heroes=parseSelection(site.heroSelection,defaultHeroSelection),stories=parseSelection(site.storySelection,defaultStorySelection);
 adminShell(adminHeading('Nội dung website','Chỉnh lời giới thiệu, liên hệ và những ảnh khách nhìn thấy đầu tiên.')+`<section class="panel settings-panel"><form data-form="settings">${fields.map(([k,v])=>`<label>${v}${['headline','intro','about','bookingNote'].includes(k)?`<textarea name="${k}" rows="${k==='about'?5:2}" ${k==='headline'?'required':''}>${esc(site[k])}</textarea>`:`<input name="${k}" value="${esc(site[k])}" ${['brand','name'].includes(k)?'required':''} ${k==='email'?'type="email"':''}>`}</label>`).join('')}<p class="form-note">Email, Facebook, Instagram và Zalo có thể để trống. Website chỉ hiện những kênh bạn đã điền.</p><p class="form-error" role="alert"></p><button class="btn" type="submit">Lưu nội dung</button></form></section>
 <section class="panel settings-panel"><h2>Ảnh chân dung của bạn</h2><p class="panel-note">Dùng ảnh chân dung hoặc ảnh bạn đang tác nghiệp. Ảnh này sẽ xuất hiện công khai ở trang Về mình.</p>${site.portrait?`<img class="portrait-preview" src="/portrait/${esc(site.portrait)}" alt="Ảnh chân dung hiện tại">`:''}<form data-form="portrait"><label>Chọn ảnh JPEG, PNG hoặc WebP · Tối đa 8 MB<input type="file" name="portrait" accept="image/jpeg,image/png,image/webp" required></label><p class="form-error" role="alert"></p><button class="btn" type="submit">Tải ảnh chân dung</button></form>${site.portrait?'<button class="underlink" data-action="hide-portrait">Ẩn ảnh chân dung</button>':''}</section>
 <section class="panel settings-panel"><form data-form="curation"><h2>Ảnh mở đầu & bộ ảnh nổi bật</h2><p class="panel-note">Chọn tối đa 4 slide và 6 bộ ảnh theo thứ tự. Mỗi album chỉ chọn một lần trong mỗi nhóm. Chỉ album công khai xuất hiện ở đây; hãy dùng ảnh khác nhau giữa slideshow và danh sách bên dưới.</p><h3>Slideshow</h3><div class="curation-grid">${Array.from({length:4},(_,i)=>curationRow('hero',i,heroes[i])).join('')}</div><h3>Bộ ảnh trên trang chủ</h3><div class="curation-grid">${Array.from({length:6},(_,i)=>curationRow('story',i,stories[i])).join('')}</div><p class="form-note">Các vị trí chưa chọn được bỏ qua. Nếu chưa chọn ảnh mở đầu, website dùng một ảnh từ portfolio. Danh sách bộ ảnh tự bổ sung các album công khai còn lại để đủ tối đa 6 bộ.</p><p class="form-error" role="alert"></p><button class="btn" type="submit">Lưu lựa chọn ảnh</button></form></section>
 <section class="panel backup-panel"><h2>Sao lưu dữ liệu</h2><p>Tải cấu trúc album, lựa chọn và yêu cầu. File JSON không chứa file ảnh; cần sao lưu kho ảnh riêng.</p><a class="small-btn" href="/api/admin/export">Tải bản sao JSON</a></section>`);
}
function editDialog(title,html){$('#editor').innerHTML=`<div class="dialog-heading"><h2 id="editor-title">${title}</h2><button class="close" data-action="close-editor" aria-label="Đóng">×</button></div>${html}`;$('#editor').setAttribute('aria-labelledby','editor-title');$('#editor').showModal();}
async function refreshAdmin(){if(adminView==='dashboard')return dashboard();if(['portfolio','clients'].includes(adminView)||adminAlbumId){adminAlbums=await api('/api/admin/albums');if(adminAlbumId)return adminAlbumDetail();return adminAlbumsPage();}if(adminView==='inquiries'){inquiries=await api('/api/admin/inquiries');return inquiriesPage();}if(adminView==='calendar'){[dates,inquiries]=await Promise.all([api('/api/admin/dates'),api('/api/admin/inquiries')]);return calendarAdmin();}if(adminView==='settings'){const values=await Promise.all([api('/api/site'),api('/api/admin/albums')]);site=currentCopy(values[0]);adminAlbums=values[1];return settingsPage();}}
async function openAdmin(){const session=await api('/api/admin/session');if(!session.authenticated)return loginPage(session);return refreshAdmin();}
async function route(){document.body.classList.toggle('public-view',location.pathname.replace(/\/$/,'')!=='/admin');site=currentCopy(await api('/api/site'));const pathname=location.pathname.replace(/\/$/,'')||'/';if(pathname==='/admin'){const hash=location.hash.slice(1);if(hash.startsWith('album/')&&/^[a-f0-9]{32}$/.test(hash.slice(6))){adminAlbumId=hash.slice(6);adminView='portfolio';}else if(views.some(v=>v[0]===hash))adminView=hash;return openAdmin();}if(pathname.startsWith('/gallery/')){album=await api('/api/gallery/'+pathname.split('/')[2]);return album.locked?lockedGallery():albumPage(true);}if(pathname.startsWith('/album/')){[album,albums]=await Promise.all([api('/api/albums/'+pathname.split('/')[2]),api('/api/portfolio?view=cards').catch(()=>[])]);return albumPage();}if(pathname==='/contact'){availability={blocked:[],loading:true,today:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())};const [year,month]=availability.today.split('-').map(Number);calendarMonth=new Date(year,month-1,1);contact();return loadBookingAvailability();}if(pathname==='/about')return about();if(['/','/portfolio'].includes(pathname)){albums=await api('/api/portfolio?view=cards');return pathname==='/'?home():portfolio();}publicPage(`<section class="page-width page-title">${label('404')}<h1>Câu chuyện này chưa có.</h1>${button('Về trang chủ','/')}</section>`);}
function closeMobileMenu(restoreFocus=false){const trigger=$('[data-action=menu]');if(trigger?.getAttribute('aria-expanded')!=='true')return;trigger.setAttribute('aria-expanded','false');$('#nav-links')?.classList.remove('open');if(restoreFocus)trigger.focus();}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobileMenu(true);});
document.addEventListener('click',e=>{if(!e.target.closest('.public-nav'))closeMobileMenu();});
function lightPhotos(){if(album?.photos)return selectedOnly?album.photos.filter(p=>p.selected):album.photos;return [];}
function showLight(index){const photos=lightPhotos();if(!photos.length)return;lightIndex=(index+photos.length)%photos.length;const p=photos[lightIndex];if($('#lightbox img').getAttribute('src')!==p.src){$('#lightbox').classList.add('image-loading');$('#lightbox').classList.remove('image-error');$('#lightbox img').src=p.src;}$('#lightbox img').alt=p.caption;$('#lightbox figcaption').textContent=`${p.caption} · ${lightIndex+1} / ${photos.length}`;const pick=$('#lightbox-pick');pick.hidden=!clientGallery;pick.dataset.photo=p.id;pick.disabled=pickBusy;pick.setAttribute('aria-pressed',String(!!p.selected));pick.textContent=p.selected?'Bỏ chọn ảnh này':'Chọn ảnh này';$('#lightbox-selection').textContent=clientGallery?`${album.photos.filter(p=>p.selected).length} ảnh đã chọn · Lựa chọn được lưu tự động`:'';if(!$('#lightbox').open)$('#lightbox').showModal();document.body.classList.add('modal-open');}
const lightImage=$('#lightbox img');
lightImage.addEventListener('load',()=>$('#lightbox').classList.remove('image-loading'));
lightImage.addEventListener('error',()=>{$('#lightbox').classList.remove('image-loading');$('#lightbox').classList.add('image-error');$('#lightbox figcaption').textContent='Chưa tải được ảnh. Hãy chuyển sang ảnh khác rồi thử lại.';});
$('#lightbox').addEventListener('close',()=>document.body.classList.remove('modal-open'));
$('#lightbox').addEventListener('click',e=>{if(e.target===$('#lightbox'))$('#lightbox').close();});
document.addEventListener('keydown',e=>{if($('#lightbox').open){if(!pickBusy&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();showLight(lightIndex+(e.key==='ArrowLeft'?-1:1));}}});
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;if(uploadBusy){toast('Đang upload ảnh. Hãy đợi hoàn tất trước khi chuyển trang.');return;}const action=el.dataset.action;if(pickBusy&&['submit-picks','selected-only','lock-gallery','next-photo','prev-photo','open-photo'].includes(action)){toast('Đang lưu lựa chọn. Vui lòng đợi một chút.');return;}try{
 if(action==='hide-portrait'){await send('/api/admin/settings',{portrait:''},'PATCH');await refreshAdmin();toast('Đã ẩn ảnh chân dung.');}
 if(action==='menu'){const open=el.getAttribute('aria-expanded')!=='true';el.setAttribute('aria-expanded',String(open));$('#nav-links').classList.toggle('open',open);}
 if(action==='filter'){filter=el.dataset.filter;portfolio();$(`[data-filter="${filter}"]`)?.focus({preventScroll:true});}
 if(action==='open-photo')showLight(lightPhotos().findIndex(p=>p.id===el.dataset.photo));
 if(action==='close-lightbox')$('#lightbox').close();if(action==='prev-photo')showLight(lightIndex-1);if(action==='next-photo')showLight(lightIndex+1);
 if(action==='pick'){
 if(pickBusy)return;const p=album.photos.find(p=>p.id===el.dataset.photo);if(!p)return;pickBusy=true;el.disabled=true;const wasOpen=$('#lightbox').open;
 try{await send(`/api/gallery/${album.id}/selection/${p.id}`,{selected:!p.selected},'PUT');p.selected=!p.selected;album.selection_status='draft';
 if(selectedOnly)albumPage(true);else{const count=album.photos.filter(p=>p.selected).length;$('.client-toolbar strong').textContent=`${count} ảnh đã chọn`;const submit=$('[data-action=submit-picks]');submit.disabled=!count;submit.textContent='Gửi lựa chọn';$('.success-note')?.remove();const gridPick=$(`.pick[data-photo="${p.id}"]`);if(gridPick){gridPick.classList.toggle('picked',p.selected);gridPick.setAttribute('aria-pressed',String(p.selected));gridPick.setAttribute('aria-label',`${p.selected?'Bỏ chọn':'Chọn'} ảnh ${p.caption}`);gridPick.textContent=p.selected?'♥':'♡';}}
 }finally{pickBusy=false;el.disabled=false;}
 if(wasOpen&&$('#lightbox').open){const photos=lightPhotos();if(!photos.length){$('#lightbox').close();$('[data-action=selected-only]')?.focus();}else showLight(selectedOnly?Math.min(lightIndex,photos.length-1):photos.findIndex(x=>x.id===p.id));}
 }

 if(action==='lock-gallery'){await send(`/api/gallery/${album.id}/logout`,{});album=null;selectedOnly=false;await route();}
 if(action==='selected-only'){selectedOnly=!selectedOnly;albumPage(true);}
 if(action==='submit-picks'){el.disabled=true;await send(`/api/gallery/${album.id}/submit`,{});album.selection_status='submitted';albumPage(true);toast('Lựa chọn của bạn đã được gửi đến studio.');}
 if(action==='month-prev'||action==='month-next'){calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+(action==='month-next'?1:-1),1);$('#booking-calendar').innerHTML=calendarHTML();($('#booking-calendar').querySelector(`[data-action="${action}"]:not(:disabled)`)||$('#booking-calendar').querySelector('[data-action="month-next"]'))?.focus();}
 if(action==='retry-calendar'){await loadBookingAvailability();}
 if(action==='choose-date'){const input=$('#booking-form [name=date]');if(input){input.value=el.dataset.date;syncBookingDate();$(`[data-action=choose-date][data-date="${bookingDate}"]`)?.focus();}}
 if(action==='clear-date'){$('#booking-form [name=date]').value='';syncBookingDate();$('#booking-form [name=date]').focus();}
 if(action==='admin-view'){adminView=el.dataset.view;adminAlbumId=null;await refreshAdmin();}
 if(action==='logout'){await send('/api/admin/logout',{});await openAdmin();}
 if(action==='new-album')editDialog(adminView==='clients'?'Tạo gallery riêng':'Tạo album mới',albumForm());
 if(action==='close-editor')$('#editor').close();
 if(action==='edit-album'){adminAlbums=await api('/api/admin/albums');adminAlbumId=el.dataset.id;const a=adminAlbums.find(a=>a.id===adminAlbumId);adminView=a?.status==='private'?'clients':'portfolio';adminAlbumDetail();}
 if(action==='album-back'){adminAlbumId=null;await refreshAdmin();}
 if(action==='album-settings')editDialog('Thông tin album',albumForm(adminAlbums.find(a=>a.id===el.dataset.id)));
 if(action==='copy-link'){await navigator.clipboard.writeText(location.origin+'/gallery/'+el.dataset.id);toast('Đã sao chép link. Hãy gửi mật khẩu riêng cho khách.');}
 if(action==='cover-photo'){const a=adminAlbums.find(a=>a.id===adminAlbumId);await send('/api/admin/albums/'+a.id,{...a,cover_id:el.dataset.id},'PATCH');await refreshAdmin();toast('Đã cập nhật ảnh bìa.');}
 if(action==='caption-photo'){const p=adminAlbums.flatMap(a=>a.photos).find(p=>p.id===el.dataset.id);editDialog('Chú thích ảnh',`<form data-form="caption" data-id="${p.id}"><label>Chú thích<input name="caption" value="${esc(p.caption)}" maxlength="300" required></label><p class="form-error" role="alert"></p><button class="btn">Lưu chú thích</button></form>`);}
 if(action==='move-photo'){const a=adminAlbums.find(a=>a.id===adminAlbumId),index=a.photos.findIndex(p=>p.id===el.dataset.id),target=index+(el.dataset.direction==='up'?-1:1);if(target>=0&&target<a.photos.length){const ordered=[...a.photos];[ordered[index],ordered[target]]=[ordered[target],ordered[index]];el.disabled=true;await send('/api/admin/albums/'+a.id+'/order',{photos:ordered.map(p=>p.id)},'PUT');await refreshAdmin();}}
 if(action==='remove-photo')editDialog('Xóa ảnh này?',`<p class="panel-note">Ảnh sẽ bị xóa khỏi album và kho lưu trữ. Hãy giữ bản gốc trên máy của bạn.</p><button class="btn danger" data-action="confirm-remove-photo" data-id="${el.dataset.id}">Xóa ảnh</button>`);
 if(action==='confirm-remove-photo'){await api('/api/admin/photos/'+el.dataset.id,{method:'DELETE'});$('#editor').close();await refreshAdmin();toast('Đã xóa ảnh.');}
 if(action==='inquiry-detail'){
 inquiries=await api('/api/admin/inquiries');const r=inquiries.find(r=>r.id===el.dataset.id);if(!r)throw Error('Yêu cầu này không còn tồn tại.');
 editDialog('Yêu cầu của '+esc(r.name),`<div class="inquiry-summary">${badge(r.status)}<span>Mã yêu cầu: ${esc(r.id.slice(0,8))}</span></div><dl class="inquiry-detail"><dt>Email</dt><dd>${r.email?`<a href="mailto:${esc(r.email)}">${esc(r.email)}</a>`:'Chưa cung cấp'}</dd><dt>Điện thoại</dt><dd>${r.phone?`<a href="tel:${esc(r.phone.replace(/[^+\d]/g,''))}">${esc(r.phone)}</a>`:'Chưa cung cấp'}</dd><dt>Dịch vụ</dt><dd>${esc(r.service)}</dd><dt>Ngân sách dự kiến</dt><dd>${esc(r.budget||'Chưa xác định')}</dd><dt>Lời nhắn của khách</dt><dd class="message">${esc(r.message)}</dd></dl><form data-form="inquiry-status" data-id="${r.id}"><div class="form-pair"><label>Ngày chụp dự kiến<input name="date" type="date" value="${esc(r.date)}"></label><label>Trạng thái<select name="status">${['new','contacted','confirmed','completed','cancelled'].map(s=>`<option value="${s}" ${s===r.status?'selected':''}>${statuses[s]}</option>`).join('')}</select></label></div><p class="form-note">Cần chọn ngày trước khi xác nhận. Mỗi ngày chỉ nhận một lịch đã xác nhận; đổi lịch thành công sẽ mở lại ngày cũ nếu không bị chặn riêng.</p><label>Ghi chú riêng của studio<textarea name="notes" rows="4" maxlength="3000" placeholder="Địa điểm, nội dung đã trao đổi, việc cần chuẩn bị…">${esc(r.notes)}</textarea></label><p class="form-note">Ghi chú chỉ hiển thị trong quản trị và bản sao lưu dữ liệu.</p><p class="form-error" role="alert"></p><button class="btn">Lưu yêu cầu</button></form>`);
 }
 if(action==='unblock-date'){await api('/api/admin/dates/'+el.dataset.date,{method:'DELETE'});await refreshAdmin();toast('Đã mở lại ngày.');}
 }catch(err){if(err.status===401&&location.pathname==='/admin'){await openAdmin();toast('Phiên quản trị đã hết hạn. Vui lòng đăng nhập lại.');}else if(err.status===401&&location.pathname.startsWith('/gallery/')){if($('#lightbox').open)$('#lightbox').close();await route();toast('Phiên gallery đã hết hạn. Vui lòng nhập lại mật khẩu.');}else toast(err.message);el.disabled=false;}});
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-form]');if(!form)return;if(form.dataset.form==='inquiry')return;e.preventDefault();if(!form.reportValidity())return;const kind=form.dataset.form,submit=form.querySelector('[type=submit]')||form.querySelector('button'),error=form.querySelector('.form-error');submit.disabled=true;if(error)error.textContent='';const data=Object.fromEntries(new FormData(form));try{
 if(kind==='setup'||kind==='login'){await send('/api/admin/'+kind,data);await openAdmin();}
 if(kind==='unlock'){await send('/api/gallery/'+location.pathname.split('/')[2]+'/unlock',data);await route();}
 if(kind==='album'){if(form.dataset.id)await send('/api/admin/albums/'+form.dataset.id,data,'PATCH');else{const result=await send('/api/admin/albums',data);adminAlbumId=result.id;adminView=data.status==='private'?'clients':'portfolio';}$('#editor').close();await refreshAdmin();toast('Đã lưu album.');}
 if(kind==='upload'){
 const input=form.querySelector('[type=file]'),files=[...input.files];
 if(files.some(f=>f.size>8*1024*1024))throw Error('Mỗi ảnh tối đa 8MB. Hãy xuất ảnh nhỏ hơn trước khi tải.');
 let queue=uploadQueues.get(form);if(!queue||!queue.matches(files)){queue=new UploadQueue(files);uploadQueues.set(form,queue);}
 input.disabled=true;uploadBusy=true;
 try{
 await queue.run(async (batch,keys)=>{const fd=new FormData();batch.forEach(file=>fd.append('photos',file));return api('/api/admin/albums/'+form.dataset.id+'/photos',{method:'POST',body:fd,headers:{'X-Upload-Keys':JSON.stringify(keys)}});},(done,total)=>{submit.textContent=`Đã tải ${done}/${total} ảnh…`;});
 if(queue.pending.length)throw Error(`Chưa xử lý được: ${queue.pending.map(f=>f.name).join(', ')}. Bấm thử lại để chỉ tải các ảnh còn lại.`);
 await refreshAdmin();toast(`Đã thêm ${files.length} ảnh.`);
 }catch(err){
 try{adminAlbums=await api('/api/admin/albums');const a=adminAlbums.find(a=>a.id===form.dataset.id);if(form.isConnected&&a){$('.admin-photo-grid').innerHTML=managedPhotos(a);$('.admin-heading p:not(.label)').textContent=`${a.photos.length} ảnh · ${categories[a.category]}`;}}catch{}
 throw Object.assign(Error(`Đã xác nhận lưu ${queue.done.size}/${files.length} ảnh. ${err.message}`),{status:err.status});
 }finally{input.disabled=false;uploadBusy=false;}
 }
 if(kind==='caption'){await send('/api/admin/photos/'+form.dataset.id,data,'PATCH');$('#editor').close();await refreshAdmin();toast('Đã lưu chú thích.');}
 if(kind==='inquiry-status'){await send('/api/admin/inquiries/'+form.dataset.id,data,'PATCH');$('#editor').close();await refreshAdmin();toast('Đã cập nhật yêu cầu.');}
 if(kind==='block-date'){await send('/api/admin/dates',data);await refreshAdmin();toast('Đã chặn ngày trong lịch.');}
 if(kind==='portrait'){
  const file=form.querySelector('[type=file]').files[0];if(file.size>8*1024*1024)throw Error('Ảnh tối đa 8 MB.');
  await api('/api/admin/portrait',{method:'POST',body:new FormData(form)});await refreshAdmin();toast('Đã cập nhật ảnh chân dung.');
 }
 if(kind==='curation'){
  const choices=kind=>[...form.querySelectorAll(`[data-curation="${kind}"]`)].flatMap(row=>{
   const albumId=row.querySelector('[data-curation-album]').value;if(!albumId)return [];
   return [{albumId,...Object.fromEntries([...row.querySelectorAll('[data-photo-field]')].map(select=>[select.dataset.photoField,select.value]))}];
  });
  await send('/api/admin/settings',{heroSelection:JSON.stringify(choices('hero')),storySelection:JSON.stringify(choices('story'))},'PATCH');await refreshAdmin();toast('Đã lưu lựa chọn ảnh.');
 }
 if(kind==='settings'){await send('/api/admin/settings',data,'PATCH');await refreshAdmin();toast('Đã cập nhật website.');}
 }catch(err){if(err.status===401&&location.pathname==='/admin'&&!['login','setup'].includes(kind)){await openAdmin();toast('Phiên quản trị đã hết hạn. Vui lòng đăng nhập lại.');}else if(error)error.textContent=err.message;else toast(err.message);}finally{submit.disabled=false;if(kind==='upload')submit.textContent=uploadQueues.get(form)?.pending.length?'Thử lại ảnh còn lại':'Upload ảnh';}});
document.addEventListener('change',event=>{
 const row=event.target.closest('[data-curation]');if(!row)return;
 if(event.target.matches('[data-curation-album]'))row.outerHTML=curationRow(row.dataset.curation,Number(row.dataset.slot),{albumId:event.target.value});
 else if(event.target.matches('[data-photo-field]')){
  const album=adminAlbums.find(a=>a.id===row.querySelector('[data-curation-album]').value),photo=album?.photos.find(p=>p.id===event.target.value);
  if(photo)event.target.closest('label').querySelector('img').src=photo.thumb;
 }
});
route().catch(err=>publicPage(`<section class="page-width page-title">${label(err.status===404?'404':'PLEASE TRY AGAIN')}<h1>${err.status===404?'Không tìm thấy bộ ảnh.':'Chưa mở được câu chuyện.'}</h1><p>${esc(err.message)}</p>${button('Về trang chủ','/')}</section>`));
