import {icon} from './icons.mjs';
import {UploadQueue} from './upload-queue.mjs';
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories={wedding:'Ngày cưới',prewedding:'Pre-wedding',portrait:'Chân dung',lifestyle:'Lifestyle'};
const statuses={draft:'Bản nháp',published:'Công khai',private:'Gallery riêng',archived:'Đã lưu trữ',new:'Mới nhận',contacted:'Đã liên hệ',confirmed:'Đã xác nhận',completed:'Hoàn thành',cancelled:'Đã hủy',submitted:'Khách đã gửi'};
let site={},albums=[],album=null,adminAlbums=[],inquiries=[],dates=[],availability={blocked:[],today:''},adminView='dashboard',adminAlbumId=null,filter='all',selectedOnly=false,lightIndex=0,calendarMonth=new Date(),bookingDate='';
const uploadQueues=new WeakMap();let uploadBusy=false;
window.addEventListener('beforeunload',e=>{if(uploadBusy){e.preventDefault();e.returnValue='';}});
const label=s=>`<p class="label">${s}</p>`;
const button=(text,href,cls='')=>`<a class="btn ${cls}" href="${href}">${text}</a>`;
const dateLabel=s=>s?new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(s+'T12:00:00')):'Chưa chọn ngày';
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:options.body instanceof FormData?options.headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await response.json();}catch{throw Error('Không kết nối được máy chủ. Vui lòng thử lại.');}if(!response.ok){const e=new Error(data.error||'Không thực hiện được yêu cầu.');e.status=response.status;e.data=data;throw e;}return data;}
const send=(url,data,method='POST')=>api(url,{method,body:JSON.stringify(data)});
let clientGallery=false,pickBusy=false;
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
const badge=status=>`<span class="badge ${esc(status)}">${esc(statuses[status]||status)}</span>`;
const cover=a=>a.photos.find(p=>p.id===a.cover_id)||a.photos[0];
const img=(p,cls='',eager=false)=>p?`<img src="${esc(p.thumb)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async" alt="${esc(p.caption)}" width="${p.width}" height="${p.height}" class="${cls}">`:`<div class="empty-cover">${icon('image')}<span>Chưa có ảnh</span></div>`;
function nav(){const pathname=location.pathname;return `<header class="public-nav"><a class="wordmark" href="/">${esc(site.brand)}<span>${esc(site.tagline)}</span></a><button class="mobile-menu" data-action="menu" aria-expanded="false" aria-controls="nav-links">Menu ${icon('menu')}</button><nav id="nav-links" aria-label="Điều hướng"><a href="/portfolio" ${pathname.startsWith('/portfolio')?'aria-current="page"':''}>Portfolio</a><a href="/about" ${pathname==='/about'?'aria-current="page"':''}>Giới thiệu</a><a href="/contact" ${pathname==='/contact'?'aria-current="page"':''}>Liên hệ</a></nav></header>`;}
function footer(){return `<footer class="public-footer"><div class="footer-main"><a class="wordmark" href="/">${esc(site.brand)}<span>${esc(site.tagline)}</span></a><p>${esc(site.location)}</p><div>${site.email?`<a href="mailto:${esc(site.email)}">${esc(site.email)}</a>`:''}${site.instagram?`<a href="${esc(site.instagram)}" target="_blank" rel="noopener noreferrer">Instagram</a>`:''}</div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} ${esc(site.brand)}</span><a href="/admin">Studio</a><span>Photography, with feeling.</span></div></footer>`;}
function publicPage(body){$('#root').innerHTML=nav()+`<main id="main">${body}</main>`+footer();}
function albumCard(a,i=0){return `<a href="/album/${a.id}" class="album-card">${img(cover(a),'',i===0)}<div class="album-meta"><div>${label(esc(categories[a.category]))}<h3>${esc(a.title)}</h3></div></div></a>`;}
function cta(){return `<section class="public-cta page-width">${label('LET’S CREATE SOMETHING PERSONAL')}<h2>Câu chuyện tiếp theo<br>có thể là <em>của bạn.</em></h2>${button('Bắt đầu một cuộc trò chuyện','/contact')}</section>`;}
function home(){const hero=albums.find(a=>cover(a));publicPage(`<section class="new-hero page-width"><div class="hero-copy">${label('INDEPENDENT PHOTOGRAPHER · VIETNAM')}<h1>${esc(site.headline)}</h1><p>${esc(site.intro)}</p>${button('Khám phá những câu chuyện','/portfolio','btn-outline')}<div class="hero-foot"><span>Ảnh & những câu chuyện</span><span>${icon('arrow')}</span></div></div><a href="${hero?'/album/'+hero.id:'/portfolio'}" class="hero-visual ${hero?'':'is-empty'}">${hero?img(cover(hero),'',true):`<div class="empty-cover hero-placeholder"><div class="placeholder-frame">${icon('image')}<span>Mỗi câu chuyện<br>bắt đầu từ một<br><em>khoảnh khắc.</em></span><small>PORTFOLIO ĐANG ĐƯỢC CHUẨN BỊ</small></div></div>`}<span class="image-label">${hero?esc(hero.title):'Photography & stories'}</span></a></section><section class="page-width featured"><div class="section-top"><div>${label('SELECTED STORIES')}<h2>Một vài câu chuyện.<br><em>Nhiều điều để nhớ.</em></h2></div><a class="underlink" href="/portfolio">Xem tất cả</a></div><div class="album-grid">${albums.length?albums.slice(0,3).map(albumCard).join(''):'<div class="empty-state"><p>Portfolio đang được chuẩn bị. Hẹn bạn những câu chuyện mới.</p></div>'}</div></section><section class="note-section page-width">${label('THE WAY I SEE IT')}<p>${esc(site.about)}</p><a class="underlink" href="/about">Về người đứng sau ống kính</a></section>${cta()}`);}
function portfolio(){const visible=albums.filter(a=>filter==='all'||a.category===filter);publicPage(`<section class="page-width page-title">${label('THE PORTFOLIO')}<h1>Câu chuyện bằng ảnh.</h1><p>Mỗi album là một thế giới riêng. Mời bạn bước vào.</p></section><section class="page-width portfolio-section"><div class="filter-row" role="group" aria-label="Lọc portfolio">${[['all','Tất cả'],...Object.entries(categories)].map(([k,v])=>`<button data-action="filter" data-filter="${k}" aria-pressed="${filter===k}" class="${filter===k?'active':''}">${v}</button>`).join('')}</div><div class="album-grid">${visible.length?visible.map(albumCard).join(''):'<p class="empty-state">Chưa có album trong thể loại này.</p>'}</div></section>${cta()}`);}
function photosMarkup(photos,client=false){return `<div class="photo-grid">${photos.map((p,i)=>`<article class="photo-item"><button class="photo-open" data-action="open-photo" data-photo="${p.id}" aria-label="Xem ảnh ${esc(p.caption)}">${img(p)}</button><div class="photo-info"><span>${esc(p.caption||'Ảnh '+(i+1))}</span>${client?`<button class="pick ${p.selected?'picked':''}" data-action="pick" data-photo="${p.id}" aria-pressed="${!!p.selected}" aria-label="${p.selected?'Bỏ chọn':'Chọn'} ảnh ${esc(p.caption)}">${p.selected?'♥':'♡'}</button>`:''}</div></article>`).join('')}</div>`;}
function albumPage(client=false){clientGallery=client;const visible=selectedOnly?album.photos.filter(p=>p.selected):album.photos;const count=album.photos.filter(p=>p.selected).length;publicPage(`<section class="page-width page-title album-title">${label(client?'YOUR PRIVATE GALLERY':esc(categories[album.category]))}<h1>${esc(album.title)}</h1><p>${esc(album.description)}</p><div class="album-line"><span>${album.photos.length} ảnh${album.event_date?' · '+dateLabel(album.event_date):''}</span>${client?`<button class="link-btn" data-action="lock-gallery">Đóng gallery</button>`:'<a href="/portfolio">Portfolio</a>'}</div></section><section class="page-width photo-section">${client?`<div class="client-toolbar"><div><strong>${count} ảnh đã chọn</strong><p>Bấm ♡ để chọn ảnh. Lựa chọn được lưu khi bạn bấm.</p></div><button class="small-btn" data-action="selected-only" aria-pressed="${selectedOnly}">${selectedOnly?'Xem tất cả':'Chỉ xem đã chọn'}</button><button class="btn" data-action="submit-picks" ${!count?'disabled':''}>${album.selection_status==='submitted'?'Gửi lại lựa chọn':'Gửi lựa chọn'}</button></div>${album.selection_status==='submitted'?'<p class="success-note">Lựa chọn đã được gửi đến studio. Bạn có thể tiếp tục chỉnh và gửi lại.</p>':''}`:''}${visible.length?photosMarkup(visible,client):`<div class="empty-state">${selectedOnly?'Bạn chưa chọn ảnh nào.':'Bộ ảnh đang được chuẩn bị.'}</div>`}</section>${client?'':cta()}`);}
function lockedGallery(){publicPage(`<section class="gallery-lock page-width">${label('A LITTLE SPACE, JUST FOR YOU')}<div class="lock-icon">${icon('lock')}</div><h1>Gallery của bạn.</h1><p>Nhập mật khẩu được nhiếp ảnh gia chia sẻ để xem và chọn ảnh.</p><form data-form="unlock"><label>Mật khẩu gallery<input name="password" type="password" autocomplete="current-password" required autofocus></label><p class="form-error" role="alert"></p><button class="btn">Mở bộ ảnh </button></form></section>`);}
function about(){publicPage(`<section class="page-width page-title">${label('BEHIND THE CAMERA')}<h1>Một góc nhìn.<br><em>Một cách kể chuyện.</em></h1></section><section class="page-width about-layout"><div class="about-art">${img(albums.flatMap(a=>a.photos).find(p=>p.height>p.width)||albums.flatMap(a=>a.photos)[0])}</div><div>${label(esc(site.brand)+' / PHOTOGRAPHER')}<h2>Xin chào,<br>mình là ${esc(site.brand)}.</h2><p class="long-copy">${esc(site.about)}</p><p>${esc(site.location)}</p>${button('Cùng lên ý tưởng','/contact')}</div></section>${cta()}`);}
function calendarHTML(){
 const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth();
 const start=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate();
 const earliest=availability.today.slice(0,7),current=`${year}-${String(month+1).padStart(2,'0')}`;
 return `<div class="calendar-heading"><button type="button" data-action="month-prev" aria-label="Tháng trước" ${current<=earliest?'disabled':''}>←</button><strong aria-live="polite">Tháng ${month+1}, ${year}</strong><button type="button" data-action="month-next" aria-label="Tháng tiếp theo">→</button></div><div class="calendar-grid">${['T2','T3','T4','T5','T6','T7','CN'].map(d=>`<span class="weekday">${d}</span>`).join('')}${Array.from({length:start},()=>'<span></span>').join('')}${Array.from({length:days},(_,i)=>{
 const d=`${current}-${String(i+1).padStart(2,'0')}`,busy=availability.blocked.includes(d),past=d<availability.today;
 return `<button type="button" data-action="choose-date" data-date="${d}" class="${busy?'busy ':''}${d===bookingDate?'chosen':''}" ${busy||past?'disabled':''} aria-pressed="${d===bookingDate}" ${d===availability.today?'aria-current="date"':''} aria-label="${dateLabel(d)}${busy?' — đã kín lịch':past?' — đã qua':''}">${i+1}</button>`;
 }).join('')}</div><div class="calendar-legend"><span><i></i>Có thể gửi yêu cầu</span><span><i class="busy"></i>Đã kín lịch</span></div>`;
}
function syncBookingDate(followMonth=false){
 const input=$('#booking-form [name=date]');if(!input)return;
 bookingDate=input.value;
 if(followMonth&&bookingDate){const [year,month]=bookingDate.split('-').map(Number);calendarMonth=new Date(year,month-1,1);}
 const busy=availability.blocked.includes(bookingDate);
 input.setCustomValidity(busy?'Ngày này đã kín lịch. Vui lòng chọn ngày khác.':'');
 input.setAttribute('aria-invalid',String(!input.validity.valid));
 const feedback=$('#booking-date-feedback');
 feedback.textContent=busy?'Ngày này đã kín lịch. Vui lòng chọn ngày khác.':bookingDate&&bookingDate<availability.today?'Vui lòng chọn ngày từ hôm nay trở đi.':bookingDate?`Ngày dự kiến: ${dateLabel(bookingDate)}. Studio sẽ xác nhận sau khi trao đổi.`:'Chưa chọn ngày? Bạn vẫn có thể gửi yêu cầu để được tư vấn.';
 feedback.classList.toggle('date-unavailable',!input.validity.valid);
 $('[data-action=clear-date]').hidden=!bookingDate;
 $('#booking-calendar').innerHTML=calendarHTML();
}
function contact(){publicPage(`<section class="page-width page-title">${label('LET’S PLAN YOUR STORY')}<h1>Bắt đầu bằng<br><em>một lời chào.</em></h1><p>${esc(site.bookingNote)}</p></section><section class="page-width booking-layout"><aside><h2>Ngày nào<br>là ngày của bạn?</h2><div id="booking-calendar">${calendarHTML()}</div><div class="contact-links">${site.email?`<a href="mailto:${esc(site.email)}">${esc(site.email)}</a>`:''}${site.phone?`<a href="tel:${esc(site.phone.replace(/[^+\d]/g,''))}">${esc(site.phone)}</a>`:''}<p>${esc(site.location)}</p></div></aside><form data-form="inquiry" id="booking-form"><div class="form-pair"><label>Tên của bạn *<input name="name" autocomplete="name" required maxlength="100" placeholder="Mình nên gọi bạn là…"></label><label>Email *<input name="email" autocomplete="email" type="email" required maxlength="150" placeholder="Email để trao đổi"></label></div><div class="form-pair"><label>Điện thoại<input name="phone" type="tel" autocomplete="tel" maxlength="30" placeholder="Số điện thoại của bạn"></label><div class="booking-date-field"><label>Ngày dự kiến<input name="date" type="date" min="${availability.today}" value="${bookingDate}" aria-describedby="booking-date-feedback"></label><button type="button" class="link-btn" data-action="clear-date" hidden>Bỏ chọn ngày</button></div></div><p class="form-note booking-date-feedback" id="booking-date-feedback" role="status">Chưa chọn ngày? Bạn vẫn có thể gửi yêu cầu để được tư vấn.</p><label>Dịch vụ<select name="service">${Object.values(categories).map(c=>`<option>${c}</option>`).join('')}<option>Quay phim</option><option>Tư vấn khác</option></select></label><label>Kể mình nghe về kế hoạch của bạn *<textarea name="message" required minlength="10" maxlength="5000" rows="5" placeholder="Địa điểm, ý tưởng, số người hoặc những điều bạn muốn lưu giữ…"></textarea></label><div class="trap" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off"></div><p class="form-note">Thông tin dùng để tư vấn và liên hệ về buổi chụp. Studio sẽ xác nhận lịch sau khi trao đổi với bạn.</p><p class="form-error" role="alert"></p><button class="btn" type="submit">Gửi yêu cầu </button></form></section>`);}
function loginPage(session){if($('#editor').open)$('#editor').close();if($('#lightbox').open)$('#lightbox').close();$('#root').innerHTML=`<main id="main" class="login-page"><a href="/" class="wordmark">${esc(site.brand)}<span>THE STUDIO</span></a><div class="login-card">${label(session.needsSetup?'WELCOME TO YOUR STUDIO':'YOUR CREATIVE WORKSPACE')}<h1>${session.needsSetup?'Bắt đầu studio.':'Chào mừng trở lại.'}</h1><p>${session.needsSetup?'Tạo tài khoản quản trị của bạn để bắt đầu quản lý website.':'Đăng nhập để quản lý portfolio, gallery và lịch chụp.'}</p><form data-form="${session.needsSetup?'setup':'login'}"><label>Email quản trị<input type="email" name="email" required autocomplete="username"></label><label>Mật khẩu<input type="password" name="password" required ${session.needsSetup?'minlength="12"':''} autocomplete="${session.needsSetup?'new-password':'current-password'}"></label>${session.needsSetup?'<p class="form-note">Mật khẩu tối thiểu 12 ký tự. Bạn tự đặt và giữ mật khẩu này.</p><label>Mã thiết lập <span class="muted">(chỉ cần trên hosting)</span><input name="token" type="password" autocomplete="off"></label>':''}<p class="form-error" role="alert"></p><button class="btn">${session.needsSetup?'Tạo studio':'Đăng nhập'} </button></form></div><a class="underlink" href="/">Về website</a></main>`;}
const views=[['dashboard','grid','Tổng quan'],['portfolio','image','Portfolio'],['clients','gallery','Gallery khách'],['inquiries','inbox','Yêu cầu đặt lịch'],['calendar','calendar','Lịch chụp'],['settings','settings','Website']];
function alignAdminNav(){
 const nav=$('.sidebar nav'),active=nav?.querySelector('[aria-current=page]');
 if(!nav||!active||!window.matchMedia('(max-width:750px)').matches)return;
 const navRect=nav.getBoundingClientRect(),activeRect=active.getBoundingClientRect();
 nav.scrollLeft+=activeRect.left-navRect.left-(nav.clientWidth-activeRect.width)/2;
}
window.addEventListener('resize',alignAdminNav);
function adminShell(content){history.replaceState(null,'','#'+(adminAlbumId?'album/'+adminAlbumId:adminView));$('#root').innerHTML=`<div class="admin-layout"><aside class="sidebar"><a class="wordmark" href="/">${esc(site.brand)}<span>THE STUDIO</span></a><p class="sidebar-label">QUẢN LÝ STUDIO</p><nav aria-label="Điều hướng studio">${views.map(([v,glyph,text])=>`<button data-action="admin-view" data-view="${v}" class="${adminView===v?'active':''}" ${adminView===v?'aria-current="page"':''}>${icon(glyph)}<span>${text}</span></button>`).join('')}</nav><div class="sidebar-bottom"><span class="studio-signature">Một nơi cho những câu chuyện.</span><button data-action="logout">${icon('logout')} Đăng xuất</button></div></aside><main id="main" class="admin-main"><header class="admin-topbar"><div class="breadcrumb"><span>Studio</span><span aria-hidden="true">/</span><strong>${esc(views.find(v=>v[0]===adminView)?.[2])}</strong></div><a href="/" target="_blank" rel="noopener">Xem website ${icon('external')}</a></header><div class="admin-content">${content}</div></main></div>`;alignAdminNav();}
function readinessPanel(r){return `<section class="panel readiness-panel"><div class="panel-heading"><h2>Chuẩn bị mở studio</h2><span class="badge">${r.production?'Đang chạy production':'Bản xem trước trên máy'}</span></div><div class="readiness-grid">${[[r.contact,'Thông tin liên hệ',r.contact?'Khách đã có kênh liên hệ với bạn.':'Thêm email hoặc số điện thoại trong Website.','settings'],[r.portfolio,'Portfolio đầu tiên',r.portfolio?'Đã có bộ ảnh công khai kèm ảnh.':'Đăng ảnh rồi chuyển album sang công khai.','portfolio'],[r.cloud,'Lưu trữ trên host',r.cloud?'Đã cấu hình database và kho ảnh cloud.':'Dữ liệu đang lưu trên máy; cần cấu hình khi đưa lên host.','settings']].map(([done,title,note,view])=>`<button class="readiness-item" data-action="admin-view" data-view="${view}"><span class="readiness-icon ${done?'done':''}">${done?icon('check'):icon('plus')}</span><div><strong>${title}</strong><p>${note}</p></div></button>`).join('')}</div></section>`;}
function adminHeading(title,subtitle,action=''){return `<div class="admin-heading"><div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`;}
function inquiryRows(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Buổi chụp</th><th>Ngày dự kiến</th><th>Trạng thái</th><th><span class="sr-only">Thao tác</span></th></tr></thead><tbody>${rows.map(r=>`<tr data-search="${esc([r.name,r.email,r.phone,r.service,r.date].join(' '))}" data-status="${r.status}"><td class="customer-cell" data-label="Khách hàng"><strong>${esc(r.name)}</strong><small>${esc(r.email)}</small></td><td data-label="Dịch vụ">${esc(r.service)}</td><td data-label="Ngày dự kiến">${dateLabel(r.date)}</td><td class="status-cell" data-label="Trạng thái">${badge(r.status)}</td><td class="row-action"><button class="link-btn" data-action="inquiry-detail" data-id="${r.id}" aria-label="Xem yêu cầu của ${esc(r.name)}">Xem chi tiết ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty-state"><span class="empty-icon">${icon('inbox')}</span><h3>Chưa có yêu cầu đặt lịch</h3><p>Khi khách gửi lời nhắn, bạn sẽ thấy tại đây.</p></div>`;}
async function dashboard(){const d=await api('/api/admin/dashboard');const count=(rows,status)=>Number(rows.find(r=>r.status===status)?.count||0);adminShell(adminHeading('Tổng quan','Mọi câu chuyện, cuộc hẹn và lựa chọn trong studio.',`<button class="btn" data-action="new-album">${icon('plus')} Tạo album</button>`)+`<div class="stats-grid">${[['Portfolio công khai',count(d.albums,'published'),'Bộ ảnh đang hiển thị'],['Gallery khách',count(d.albums,'private'),'Không gian riêng cho khách'],['Yêu cầu mới',count(d.inquiries,'new'),'Đang chờ bạn xử lý'],['Ảnh trong studio',d.photos,'Khoảnh khắc được lưu giữ']].map(([title,n,note])=>`<div class="stat-card"><span>${title}</span><strong>${n}</strong><small>${note}</small></div>`).join('')}</div>${readinessPanel(d.readiness)}<section class="panel"><div class="panel-heading"><h2>Yêu cầu gần đây</h2><button class="link-btn" data-action="admin-view" data-view="inquiries">Xem tất cả</button></div>${inquiryRows(d.recent)}</section><div class="admin-two"><section class="panel quick-start"><h2>Bắt đầu một bộ ảnh.</h2><p>Tạo album, thêm ảnh, chọn bìa và chuyển sang công khai khi đã sẵn sàng.</p><button class="underlink" data-action="new-album">Tạo album đầu tiên</button></section><section class="panel"><h2>Khách đã gửi lựa chọn</h2>${d.selections.length?d.selections.map(a=>`<button class="selection-alert" data-action="edit-album" data-id="${a.id}"><span>${esc(a.title)}</span></button>`).join(''):'<p class="muted panel-note">Khi khách gửi danh sách ảnh đã chọn, bạn sẽ thấy gallery tại đây.</p>'}</section></div>`);}
function adminAlbumsPage(){const client=adminView==='clients';const rows=adminAlbums.filter(a=>client?a.status==='private':a.status!=='private');adminShell(adminHeading(client?'Gallery khách':'Portfolio',client?'Chia sẻ link và mật khẩu. Khách xem ảnh, chọn và gửi lại cho studio.':'Tạo bộ ảnh, sắp xếp nội dung và chọn những gì sẽ hiển thị trên website.',`<button class="btn" data-action="new-album">${icon('plus')} ${client?'Tạo gallery':'Tạo album'}</button>`)+searchToolbar(client?['private']:['draft','published','archived'])+`<div class="admin-album-grid">${rows.length?rows.map(a=>`<button class="admin-album" data-search="${esc([a.title,a.client_name,categories[a.category]].join(' '))}" data-status="${a.status}" data-action="edit-album" data-id="${a.id}">${img(cover(a))}<div class="admin-album-info">${badge(a.status)}<h3>${esc(a.title)}</h3><p>${a.photos.length} ảnh · ${esc(categories[a.category])}${client?' · '+a.photos.filter(p=>p.selected).length+' đã chọn':''}</p>${a.selection_status==='submitted'&&client?'<span class="pick-status">● Khách đã gửi lựa chọn</span>':''}</div></button>`).join(''):`<div class="empty-state"><span class="empty-icon">${icon('image')}</span><h3>${client?'Gallery đầu tiên của bạn':'Bộ ảnh đầu tiên của bạn'}</h3><p>${client?'Tạo gallery để chia sẻ ảnh riêng với khách.':'Thêm một bộ ảnh để bắt đầu câu chuyện.'}</p></div>`}</div>`);applyAdminFilters();}
function albumForm(a={}){return `<form data-form="album" data-id="${a.id||''}"><label>Tên album *<input name="title" required maxlength="150" value="${esc(a.title)}" placeholder="Tên câu chuyện của bạn"></label><div class="form-pair"><label>Thể loại<select name="category">${Object.entries(categories).map(([k,v])=>`<option value="${k}" ${a.category===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Trạng thái<select name="status">${['draft','published','private','archived'].map(k=>`<option value="${k}" ${(a.status|| (adminView==='clients'?'private':'draft'))===k?'selected':''}>${statuses[k]}</option>`).join('')}</select></label></div><label>Mô tả<textarea name="description" rows="3" maxlength="2000">${esc(a.description)}</textarea></label><div class="form-pair"><label>Tên khách hàng<input name="client_name" maxlength="150" value="${esc(a.client_name)}"></label><label>Ngày chụp<input name="event_date" type="date" value="${esc(a.event_date)}"></label></div><label>Mật khẩu gallery riêng<input name="password" type="password" autocomplete="new-password" minlength="8" placeholder="${a.has_password?'Để trống nếu giữ mật khẩu hiện tại':'Ít nhất 8 ký tự nếu chọn gallery riêng'}"></label><p class="form-note">Chỉ trạng thái công khai hiển thị trên portfolio. Gallery riêng cần mật khẩu; đổi mật khẩu sẽ yêu cầu khách đăng nhập lại.</p><p class="form-error" role="alert"></p><button class="btn">${a.id?'Lưu thay đổi':'Tạo album'} </button></form>`;}
function managedPhotos(a){return a.photos.map((p,i)=>`<article class="manage-photo ${p.selected?'client-picked':''}">${img(p)}<div><span class="photo-number">${String(i+1).padStart(2,'0')}${p.selected?' · ♥ Khách chọn':''}</span><p>${esc(p.original||p.caption)}</p><div class="photo-actions"><button data-action="cover-photo" data-id="${p.id}">${a.cover_id===p.id?'● Ảnh bìa':'Đặt bìa'}</button><button data-action="caption-photo" data-id="${p.id}">Sửa</button><button data-action="move-photo" data-id="${p.id}" data-direction="up" aria-label="Đưa ảnh lên trước" ${i===0?'disabled':''}>↑</button><button data-action="move-photo" data-id="${p.id}" data-direction="down" aria-label="Đưa ảnh xuống sau" ${i===a.photos.length-1?'disabled':''}>↓</button><button data-action="remove-photo" data-id="${p.id}">Xóa</button></div></div></article>`).join('');}
function adminAlbumDetail(){const a=adminAlbums.find(a=>a.id===adminAlbumId);if(!a){adminAlbumId=null;return adminAlbumsPage();}adminView=a.status==='private'?'clients':'portfolio';const count=a.photos.filter(p=>p.selected).length;adminShell(`<button class="underlink back-btn" data-action="album-back">Danh sách album</button>`+adminHeading(esc(a.title),`${a.photos.length} ảnh · ${esc(categories[a.category])}`,`<button class="small-btn" data-action="album-settings" data-id="${a.id}">${icon('settings')} Thông tin album</button>`)+`<div class="album-detail-top">${badge(a.status)}${a.status==='published'?`<a class="underlink" href="/album/${a.id}" target="_blank" rel="noopener">Xem trên website</a>`:''}${a.status==='private'?`<button class="underlink" data-action="copy-link" data-id="${a.id}">Sao chép link gallery</button><span>${count} ảnh được chọn</span><a class="small-btn" href="/api/admin/albums/${a.id}/selections.csv">Xuất danh sách CSV</a>${badge(a.selection_status)}`:''}</div><section class="upload-panel"><div><h3>Thêm những khoảnh khắc.</h3><p>JPEG, PNG, WebP · Tối đa 8MB/ảnh. Chọn nhiều ảnh cùng lúc; ảnh được tối ưu để xem trên web.</p></div><form data-form="upload" data-id="${a.id}"><label class="upload-label">Chọn ảnh<input type="file" name="photos" accept="image/jpeg,image/png,image/webp" multiple required></label><button class="btn" type="submit">Upload ảnh</button><p class="form-error" role="alert"></p></form></section><div class="admin-photo-grid">${managedPhotos(a)}</div>`);}
const adminFilters={};
const normalizeSearch=value=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
function searchToolbar(options){const f=adminFilters[adminView]||{query:'',status:''};return `<div class="admin-filters"><label>Tìm kiếm<span class="search-input">${icon('search')}<input type="search" data-admin-search value="${esc(f.query)}" placeholder="${adminView==='inquiries'?'Tên, email hoặc số điện thoại…':'Tên album hoặc khách hàng…'}"></span></label><label>Trạng thái<select data-admin-status aria-label="Trạng thái"><option value="">Tất cả trạng thái</option>${options.map(k=>`<option value="${k}" ${f.status===k?'selected':''}>${statuses[k]}</option>`).join('')}</select></label><p data-filter-count role="status"></p></div><p class="filter-empty" hidden>Không có kết quả phù hợp. Thử từ khóa hoặc trạng thái khác.</p>`;}
function applyAdminFilters(){if(!$('[data-admin-search]'))return;const f=adminFilters[adminView]||{query:'',status:''};const rows=[...document.querySelectorAll('[data-search]')];let count=0;rows.forEach(row=>{row.hidden=!!((f.status&&row.dataset.status!==f.status)||!normalizeSearch(row.dataset.search).includes(normalizeSearch(f.query.trim())));if(!row.hidden)count++;});$('[data-filter-count]').textContent=`${count} / ${rows.length} kết quả`;$('.filter-empty').hidden=!rows.length||count>0;}
function changeAdminFilter(){adminFilters[adminView]={query:$('[data-admin-search]').value,status:$('[data-admin-status]').value};applyAdminFilters();}
document.addEventListener('input',e=>{if(e.target.matches('[data-admin-search]'))changeAdminFilter();});
document.addEventListener('change',e=>{if(e.target.matches('#booking-form [name=date]'))syncBookingDate(true);if(e.target.matches('[data-admin-status]'))changeAdminFilter();if(e.target.matches('input[type=file]')){const form=e.target.closest('[data-form=upload]');if(form){uploadQueues.delete(form);form.querySelector('button').textContent='Upload ảnh';form.querySelector('.form-error').textContent='';}}});
function inquiriesPage(){adminShell(adminHeading('Yêu cầu đặt lịch','Theo dõi cuộc hẹn và giữ mọi trao đổi ở cùng một nơi.')+searchToolbar(['new','contacted','confirmed','completed','cancelled'])+`<section class="panel">${inquiryRows(inquiries)}</section>`);applyAdminFilters();}
function calendarAdmin(){adminShell(adminHeading('Lịch chụp','Quản lý ngày bận và những buổi chụp đã xác nhận.')+`<div class="admin-two"><section class="panel"><h2>Chặn một ngày</h2><form data-form="block-date"><label>Ngày bận<input name="date" type="date" required></label><label>Ghi chú riêng<input name="note" maxlength="200" placeholder="Chụp ngoài tỉnh, nghỉ…"></label><p class="form-error" role="alert"></p><button class="btn">${icon('plus')} Chặn ngày</button></form></section><section class="panel"><h2>Ngày đã chặn</h2>${dates.length?dates.map(d=>`<div class="date-row"><div><strong>${dateLabel(d.date)}</strong><small>${esc(d.note)}</small></div><button class="link-btn" data-action="unblock-date" data-date="${d.date}">Mở lại</button></div>`).join(''):'<p class="panel-note muted">Chưa chặn ngày nào.</p>'}</section></div><section class="panel"><h2>Lịch đã xác nhận</h2>${inquiryRows(inquiries.filter(i=>i.status==='confirmed'))}</section>`);}
function settingsPage(){const fields=[['brand','Tên hiển thị'],['tagline','Dòng mô tả thương hiệu'],['headline','Tiêu đề trang chủ'],['intro','Giới thiệu ngắn'],['about','Câu chuyện của bạn'],['email','Email liên hệ'],['phone','Điện thoại'],['location','Khu vực hoạt động'],['instagram','Link Instagram'],['bookingNote','Lời nhắn ở trang đặt lịch']];adminShell(adminHeading('Nội dung website','Thông tin và lời giới thiệu mang dấu ấn của bạn.')+`<section class="panel settings-panel"><form data-form="settings">${fields.map(([k,v])=>`<label>${v}${['intro','about','bookingNote'].includes(k)?`<textarea name="${k}" rows="3">${esc(site[k])}</textarea>`:`<input name="${k}" value="${esc(site[k])}" ${['brand','headline'].includes(k)?'required':''} ${k==='email'?'type="email"':''}>`}</label>`).join('')}<p class="form-error" role="alert"></p><button class="btn">Lưu website</button></form></section><section class="panel backup-panel"><h2>Sao lưu dữ liệu</h2><p>Tải cấu trúc album, thông tin ảnh, lựa chọn và yêu cầu đặt lịch. File JSON không chứa file ảnh; cần sao lưu kho ảnh riêng.</p><a class="small-btn" href="/api/admin/export">Tải bản sao JSON</a></section>`);}
function editDialog(title,html){$('#editor').innerHTML=`<div class="dialog-heading"><h2 id="editor-title">${title}</h2><button class="close" data-action="close-editor" aria-label="Đóng">×</button></div>${html}`;$('#editor').setAttribute('aria-labelledby','editor-title');$('#editor').showModal();}
async function refreshAdmin(){if(adminView==='dashboard')return dashboard();if(['portfolio','clients'].includes(adminView)||adminAlbumId){adminAlbums=await api('/api/admin/albums');if(adminAlbumId)return adminAlbumDetail();return adminAlbumsPage();}if(adminView==='inquiries'){inquiries=await api('/api/admin/inquiries');return inquiriesPage();}if(adminView==='calendar'){[dates,inquiries]=await Promise.all([api('/api/admin/dates'),api('/api/admin/inquiries')]);return calendarAdmin();}if(adminView==='settings'){site=await api('/api/site');return settingsPage();}}
async function openAdmin(){const session=await api('/api/admin/session');if(!session.authenticated)return loginPage(session);return refreshAdmin();}
async function route(){site=await api('/api/site');const pathname=location.pathname.replace(/\/$/,'')||'/';if(pathname==='/admin'){const hash=location.hash.slice(1);if(hash.startsWith('album/')&&/^[a-f0-9]{32}$/.test(hash.slice(6))){adminAlbumId=hash.slice(6);adminView='portfolio';}else if(views.some(v=>v[0]===hash))adminView=hash;return openAdmin();}if(pathname.startsWith('/gallery/')){album=await api('/api/gallery/'+pathname.split('/')[2]);return album.locked?lockedGallery():albumPage(true);}if(pathname.startsWith('/album/')){album=await api('/api/albums/'+pathname.split('/')[2]);return albumPage();}if(pathname==='/contact'){availability=await api('/api/availability');const [year,month]=availability.today.split('-').map(Number);calendarMonth=new Date(year,month-1,1);return contact();}if(['/','/portfolio','/about'].includes(pathname)){albums=await api('/api/portfolio');return pathname==='/'?home():pathname==='/portfolio'?portfolio():about();}publicPage(`<section class="page-width page-title">${label('404')}<h1>Câu chuyện này chưa có.</h1>${button('Về trang chủ','/')}</section>`);}
function lightPhotos(){if(album?.photos)return selectedOnly?album.photos.filter(p=>p.selected):album.photos;return [];}
function showLight(index){const photos=lightPhotos();if(!photos.length)return;lightIndex=(index+photos.length)%photos.length;const p=photos[lightIndex];if($('#lightbox img').getAttribute('src')!==p.src)$('#lightbox img').src=p.src;$('#lightbox img').alt=p.caption;$('#lightbox figcaption').textContent=`${p.caption} · ${lightIndex+1} / ${photos.length}`;const pick=$('#lightbox-pick');pick.hidden=!clientGallery;pick.dataset.photo=p.id;pick.disabled=pickBusy;pick.setAttribute('aria-pressed',String(!!p.selected));pick.textContent=p.selected?'Bỏ chọn ảnh này':'Chọn ảnh này';$('#lightbox-selection').textContent=clientGallery?`${album.photos.filter(p=>p.selected).length} ảnh đã chọn · Lựa chọn được lưu tự động`:'';if(!$('#lightbox').open)$('#lightbox').showModal();document.body.classList.add('modal-open');}
$('#lightbox').addEventListener('close',()=>document.body.classList.remove('modal-open'));
$('#lightbox').addEventListener('click',e=>{if(e.target===$('#lightbox'))$('#lightbox').close();});
document.addEventListener('keydown',e=>{if($('#lightbox').open){if(!pickBusy&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();showLight(lightIndex+(e.key==='ArrowLeft'?-1:1));}}});
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;if(uploadBusy){toast('Đang upload ảnh. Hãy đợi hoàn tất trước khi chuyển trang.');return;}const action=el.dataset.action;if(pickBusy&&['submit-picks','selected-only','lock-gallery','next-photo','prev-photo','open-photo'].includes(action)){toast('Đang lưu lựa chọn. Vui lòng đợi một chút.');return;}try{
 if(action==='menu'){const open=el.getAttribute('aria-expanded')!=='true';el.setAttribute('aria-expanded',String(open));$('#nav-links').classList.toggle('open',open);}
 if(action==='filter'){filter=el.dataset.filter;portfolio();}
 if(action==='open-photo')showLight(lightPhotos().findIndex(p=>p.id===el.dataset.photo));
 if(action==='close-lightbox')$('#lightbox').close();if(action==='prev-photo')showLight(lightIndex-1);if(action==='next-photo')showLight(lightIndex+1);
 if(action==='pick'){
 if(pickBusy)return;const p=album.photos.find(p=>p.id===el.dataset.photo);if(!p)return;pickBusy=true;el.disabled=true;const wasOpen=$('#lightbox').open;
 try{await send(`/api/gallery/${album.id}/selection/${p.id}`,{selected:!p.selected},'PUT');p.selected=!p.selected;album.selection_status='draft';
 if(selectedOnly)albumPage(true);else{const count=album.photos.filter(p=>p.selected).length;$('.client-toolbar strong').textContent=`${count} ảnh đã chọn`;const submit=$('[data-action=submit-picks]');submit.disabled=!count;submit.textContent='Gửi lựa chọn';$('.success-note')?.remove();const gridPick=$(`.pick[data-photo="${p.id}"]`);if(gridPick){gridPick.classList.toggle('picked',p.selected);gridPick.setAttribute('aria-pressed',String(p.selected));gridPick.setAttribute('aria-label',`${p.selected?'Bỏ chọn':'Chọn'} ảnh ${p.caption}`);gridPick.textContent=p.selected?'♥':'♡';}}
 }finally{pickBusy=false;el.disabled=false;}
 if(wasOpen&&$('#lightbox').open){const photos=lightPhotos();if(!photos.length){$('#lightbox').close();$('[data-action=selected-only]')?.focus();}else showLight(selectedOnly?Math.min(lightIndex,photos.length-1):photos.findIndex(x=>x.id===p.id));}
 }

 if(action==='lock-gallery'){await send(`/api/gallery/${album.id}/logout`,{});album=null;selectedOnly=false;await route();}
 if(action==='selected-only'){selectedOnly=!selectedOnly;albumPage(true);}
 if(action==='submit-picks'){el.disabled=true;await send(`/api/gallery/${album.id}/submit`,{});album.selection_status='submitted';albumPage(true);toast('Lựa chọn của bạn đã được gửi đến studio.');}
 if(action==='month-prev'||action==='month-next'){calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+(action==='month-next'?1:-1),1);$('#booking-calendar').innerHTML=calendarHTML();}
 if(action==='choose-date'){const input=$('#booking-form [name=date]');if(input){input.value=el.dataset.date;syncBookingDate();$(`[data-action=choose-date][data-date="${bookingDate}"]`)?.focus();}}
 if(action==='clear-date'){$('#booking-form [name=date]').value='';syncBookingDate();$('#booking-form [name=date]').focus();}
 if(action==='admin-view'){adminView=el.dataset.view;adminAlbumId=null;await refreshAdmin();}
 if(action==='logout'){await send('/api/admin/logout',{});await openAdmin();}
 if(action==='new-album')editDialog(adminView==='clients'?'Tạo gallery riêng':'Tạo album mới',albumForm());
 if(action==='close-editor')$('#editor').close();
 if(action==='edit-album'){adminAlbums=await api('/api/admin/albums');adminAlbumId=el.dataset.id;const a=adminAlbums.find(a=>a.id===adminAlbumId);adminView=a?.status==='private'?'clients':'portfolio';adminAlbumDetail();}
 if(action==='album-back'){adminAlbumId=null;await refreshAdmin();}
 if(action==='album-settings')editDialog('Thông tin album',albumForm(adminAlbums.find(a=>a.id===el.dataset.id)));
 if(action==='copy-link'){await navigator.clipboard.writeText(location.origin+'/gallery/'+el.dataset.id);toast('Đã sao chép link. Hãy gửi mật khẩu riêng cho khách.');}
 if(action==='cover-photo'){const a=adminAlbums.find(a=>a.id===adminAlbumId);await send('/api/admin/albums/'+a.id,{...a,cover_id:el.dataset.id},'PATCH');await refreshAdmin();toast('Đã cập nhật ảnh bìa.');}
 if(action==='caption-photo'){const p=adminAlbums.flatMap(a=>a.photos).find(p=>p.id===el.dataset.id);editDialog('Chú thích ảnh',`<form data-form="caption" data-id="${p.id}"><label>Chú thích<input name="caption" value="${esc(p.caption)}" maxlength="300" required></label><p class="form-error" role="alert"></p><button class="btn">Lưu chú thích</button></form>`);}
 if(action==='move-photo'){const a=adminAlbums.find(a=>a.id===adminAlbumId),index=a.photos.findIndex(p=>p.id===el.dataset.id),target=index+(el.dataset.direction==='up'?-1:1);if(target>=0&&target<a.photos.length){const ordered=[...a.photos];[ordered[index],ordered[target]]=[ordered[target],ordered[index]];el.disabled=true;await send('/api/admin/albums/'+a.id+'/order',{photos:ordered.map(p=>p.id)},'PUT');await refreshAdmin();}}
 if(action==='remove-photo')editDialog('Xóa ảnh này?',`<p class="panel-note">Ảnh sẽ bị xóa khỏi album và kho lưu trữ. Hãy giữ bản gốc trên máy của bạn.</p><button class="btn danger" data-action="confirm-remove-photo" data-id="${el.dataset.id}">Xóa ảnh</button>`);
 if(action==='confirm-remove-photo'){await api('/api/admin/photos/'+el.dataset.id,{method:'DELETE'});$('#editor').close();await refreshAdmin();toast('Đã xóa ảnh.');}
 if(action==='inquiry-detail'){
 inquiries=await api('/api/admin/inquiries');const r=inquiries.find(r=>r.id===el.dataset.id);if(!r)throw Error('Yêu cầu này không còn tồn tại.');
 editDialog('Yêu cầu của '+esc(r.name),`<div class="inquiry-summary">${badge(r.status)}<span>Mã yêu cầu: ${esc(r.id.slice(0,8))}</span></div><dl class="inquiry-detail"><dt>Email</dt><dd><a href="mailto:${esc(r.email)}">${esc(r.email)}</a></dd><dt>Điện thoại</dt><dd>${r.phone?`<a href="tel:${esc(r.phone.replace(/[^+\d]/g,''))}">${esc(r.phone)}</a>`:'Chưa cung cấp'}</dd><dt>Dịch vụ</dt><dd>${esc(r.service)}</dd><dt>Lời nhắn của khách</dt><dd class="message">${esc(r.message)}</dd></dl><form data-form="inquiry-status" data-id="${r.id}"><div class="form-pair"><label>Ngày chụp dự kiến<input name="date" type="date" value="${esc(r.date)}"></label><label>Trạng thái<select name="status">${['new','contacted','confirmed','completed','cancelled'].map(s=>`<option value="${s}" ${s===r.status?'selected':''}>${statuses[s]}</option>`).join('')}</select></label></div><p class="form-note">Cần chọn ngày trước khi xác nhận. Mỗi ngày chỉ nhận một lịch đã xác nhận; đổi lịch thành công sẽ mở lại ngày cũ nếu không bị chặn riêng.</p><label>Ghi chú riêng của studio<textarea name="notes" rows="4" maxlength="3000" placeholder="Địa điểm, nội dung đã trao đổi, việc cần chuẩn bị…">${esc(r.notes)}</textarea></label><p class="form-note">Ghi chú chỉ hiển thị trong quản trị và bản sao lưu dữ liệu.</p><p class="form-error" role="alert"></p><button class="btn">Lưu yêu cầu</button></form>`);
 }
 if(action==='unblock-date'){await api('/api/admin/dates/'+el.dataset.date,{method:'DELETE'});await refreshAdmin();toast('Đã mở lại ngày.');}
 }catch(err){if(err.status===401&&location.pathname==='/admin'){await openAdmin();toast('Phiên quản trị đã hết hạn. Vui lòng đăng nhập lại.');}else if(err.status===401&&location.pathname.startsWith('/gallery/')){if($('#lightbox').open)$('#lightbox').close();await route();toast('Phiên gallery đã hết hạn. Vui lòng nhập lại mật khẩu.');}else toast(err.message);el.disabled=false;}});
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();if(!form.reportValidity())return;const kind=form.dataset.form,submit=form.querySelector('[type=submit]')||form.querySelector('button'),error=form.querySelector('.form-error');submit.disabled=true;if(error)error.textContent='';const data=Object.fromEntries(new FormData(form));try{
 if(kind==='setup'||kind==='login'){await send('/api/admin/'+kind,data);await openAdmin();}
 if(kind==='unlock'){await send('/api/gallery/'+location.pathname.split('/')[2]+'/unlock',data);await route();}
 if(kind==='inquiry'){const result=await send('/api/inquiries',data);$('#booking-calendar').innerHTML=`<p class="success-note">${data.date?'Ngày dự kiến: '+dateLabel(data.date)+'.':'Bạn chưa chọn ngày chụp.'} Studio sẽ trao đổi để xác nhận lịch với bạn.</p>`;form.innerHTML=`<div class="booking-success"><span>✓</span><h2>Đã ghi nhận<br>lời nhắn của bạn.</h2><p>Mã yêu cầu: <strong>${esc(result.reference)}</strong></p><p>Studio sẽ liên hệ qua thông tin bạn cung cấp để trao đổi và xác nhận lịch.</p>${button('Khám phá portfolio','/portfolio','btn-outline')}</div>`;}
 if(kind==='album'){if(form.dataset.id)await send('/api/admin/albums/'+form.dataset.id,data,'PATCH');else{const result=await send('/api/admin/albums',data);adminAlbumId=result.id;adminView=data.status==='private'?'clients':'portfolio';}$('#editor').close();await refreshAdmin();toast('Đã lưu album.');}
 if(kind==='upload'){
 const input=form.querySelector('[type=file]'),files=[...input.files];
 if(files.some(f=>f.size>8*1024*1024))throw Error('Mỗi ảnh tối đa 8MB. Hãy xuất ảnh nhỏ hơn trước khi tải.');
 let queue=uploadQueues.get(form);if(!queue||!queue.matches(files)){queue=new UploadQueue(files);uploadQueues.set(form,queue);}
 input.disabled=true;uploadBusy=true;
 try{
 await queue.run(async (batch,keys)=>{const fd=new FormData();batch.forEach(file=>fd.append('photos',file));return api('/api/admin/albums/'+form.dataset.id+'/photos',{method:'POST',body:fd,headers:{'X-Upload-Keys':JSON.stringify(keys)}});},(done,total)=>{submit.textContent=`Đã tải ${done}/${total} ảnh…`;});
 if(queue.pending.length)throw Error(`Chưa xử lý được: ${queue.pending.map(f=>f.name).join(', ')}. Bấm thử lại để chỉ tải các ảnh còn lại.`);
 await refreshAdmin();toast(`Đã thêm ${files.length} ảnh.`);
 }catch(err){
 try{adminAlbums=await api('/api/admin/albums');const a=adminAlbums.find(a=>a.id===form.dataset.id);if(form.isConnected&&a){$('.admin-photo-grid').innerHTML=managedPhotos(a);$('.admin-heading p:not(.label)').textContent=`${a.photos.length} ảnh · ${categories[a.category]}`;}}catch{}
 throw Object.assign(Error(`Đã xác nhận lưu ${queue.done.size}/${files.length} ảnh. ${err.message}`),{status:err.status});
 }finally{input.disabled=false;uploadBusy=false;}
 }
 if(kind==='caption'){await send('/api/admin/photos/'+form.dataset.id,data,'PATCH');$('#editor').close();await refreshAdmin();toast('Đã lưu chú thích.');}
 if(kind==='inquiry-status'){await send('/api/admin/inquiries/'+form.dataset.id,data,'PATCH');$('#editor').close();await refreshAdmin();toast('Đã cập nhật yêu cầu.');}
 if(kind==='block-date'){await send('/api/admin/dates',data);await refreshAdmin();toast('Đã chặn ngày trong lịch.');}
 if(kind==='settings'){await send('/api/admin/settings',data,'PATCH');await refreshAdmin();toast('Đã cập nhật website.');}
 }catch(err){if(kind==='inquiry'&&err.status===409){try{availability=await api('/api/availability');syncBookingDate();}catch{}}if(err.status===401&&location.pathname==='/admin'&&!['login','setup'].includes(kind)){await openAdmin();toast('Phiên quản trị đã hết hạn. Vui lòng đăng nhập lại.');}else if(error)error.textContent=err.message;else toast(err.message);}finally{submit.disabled=false;if(kind==='upload')submit.textContent=uploadQueues.get(form)?.pending.length?'Thử lại ảnh còn lại':'Upload ảnh';}});
route().catch(err=>publicPage(`<section class="page-width page-title">${label(err.status===404?'404':'PLEASE TRY AGAIN')}<h1>${err.status===404?'Không tìm thấy bộ ảnh.':'Chưa mở được câu chuyện.'}</h1><p>${esc(err.message)}</p>${button('Về trang chủ','/')}</section>`));
